import type { TranslationKey } from "@/lib/locale/i18n.utils";
import type { ChangelogEntry, ChangelogScope } from "@/types/settings";

export interface ChangelogVersion {
  version: string;
  added: ChangelogEntry[];
  changed: ChangelogEntry[];
  fixed: ChangelogEntry[];
}

function entry(key: TranslationKey, scope: ChangelogScope): ChangelogEntry {
  return { key, scope };
}

export const CHANGELOG: ChangelogVersion[] = [
  {
    version: "4.1.1",
    added: [
      entry("changelog.4_1_1.added.smart_resume", "torrents"),
      entry("changelog.4_1_1.added.paused_watch", "torrents"),
      entry("changelog.4_1_1.added.paused_changed_names", "torrents"),
      entry("changelog.4_1_1.added.paused_recheck", "torrents"),
      entry("changelog.4_1_1.added.tray", "app"),
      entry("changelog.4_1_1.added.native_toasts", "app"),
      entry("changelog.4_1_1.added.notification_targets", "app"),
      entry("changelog.4_1_1.added.file_order_setting", "torrents"),
      entry("changelog.4_1_1.added.torrent_queue", "torrents"),
      entry("changelog.4_1_1.added.torrent_queue_drag", "torrents"),
      entry("changelog.4_1_1.added.torrent_proxy", "torrents"),
      entry("changelog.4_1_1.added.screenshots", "app"),
      entry("changelog.4_1_1.added.screenshots_save", "app"),
      entry("changelog.4_1_1.added.screenshot_draw", "app"),
      entry("changelog.4_1_1.added.screenshot_modal", "app"),
      entry("changelog.4_1_1.added.browser_login", "anilist"),
      entry("changelog.4_1_1.added.friend_comments", "anilist"),
      entry("changelog.4_1_1.added.friend_rewatch", "anilist"),
      entry("changelog.4_1_1.added.list_comment", "anilist"),
      entry("changelog.4_1_1.added.search_operators", "search"),
      entry("changelog.4_1_1.added.collection_operators", "collection"),
      entry("changelog.4_1_1.added.app_site", "app"),
      entry("changelog.4_1_1.added.score_formats", "anilist"),
      entry("changelog.4_1_1.added.franchise_status", "anilist"),
      entry("changelog.4_1_1.added.wizard_dropdown", "collection"),
      entry("changelog.4_1_1.added.wizard_save_loader", "collection"),
      entry("changelog.4_1_1.added.rutracker_proxy_login", "torrents"),
    ],
    changed: [
      entry("changelog.4_1_1.changed.resume_notice", "torrents"),
      entry("changelog.4_1_1.changed.rewrite_ghost", "torrents"),
      entry("changelog.4_1_1.changed.file_selection", "torrents"),
      entry("changelog.4_1_1.changed.bulk_buttons", "torrents"),
      entry("changelog.4_1_1.changed.errors_recheck", "torrents"),
      entry("changelog.4_1_1.changed.recreate_confirm", "torrents"),
      entry("changelog.4_1_1.changed.torrent_speed", "torrents"),
      entry("changelog.4_1_1.changed.color_presets", "settings"),
      entry("changelog.4_1_1.changed.suggestion_perf", "search"),
      entry("changelog.4_1_1.changed.friend_status_square", "anilist"),
      entry("changelog.4_1_1.changed.rutracker_cookies", "torrents"),
    ],
    fixed: [
      entry("changelog.4_1_1.fixed.tray_restore", "app"),
      entry("changelog.4_1_1.fixed.text_cursor", "app"),
      entry("changelog.4_1_1.fixed.tmdb_key_save", "settings"),
    ],
  },
  {
    version: "4.1.0",
    added: [
      entry("changelog.4_1_0.added.torrent_create", "torrents"),
      entry("changelog.4_1_0.added.torrent_create_link", "torrents"),
      entry("changelog.4_1_0.added.torrent_select", "torrents"),
      entry("changelog.4_1_0.added.torrent_missing", "torrents"),
      entry("changelog.4_1_0.added.overlay_escape", "app"),
      entry("changelog.4_1_0.added.host_bars", "app"),
      entry("changelog.4_1_0.added.color_picker", "settings"),
      entry("changelog.4_1_0.added.animated_counters", "settings"),
      entry("changelog.4_1_0.added.characters_window", "anilist"),
      entry("changelog.4_1_0.added.character_cards", "anilist"),
      entry("changelog.4_1_0.added.character_tiles", "anilist"),
      entry("changelog.4_1_0.added.voice_actor_preview", "anilist"),
      entry("changelog.4_1_0.added.friends_preview", "anilist"),
      entry("changelog.4_1_0.added.detail_posters", "anilist"),
      entry("changelog.4_1_0.added.torrent_queue", "torrents"),
      entry("changelog.4_1_0.added.torrent_queue_drag", "torrents"),
    ],
    changed: [
      entry("changelog.4_1_0.changed.file_selection", "torrents"),
      entry("changelog.4_1_0.changed.bulk_buttons", "torrents"),
      entry("changelog.4_1_0.changed.errors_recheck", "torrents"),
      entry("changelog.4_1_0.changed.recreate_confirm", "torrents"),
    ],
    fixed: [
      entry("changelog.4_1_0.fixed.tracker_ipc", "torrents"),
      entry("changelog.4_1_0.fixed.anilist_pages", "anilist"),
      entry("changelog.4_1_0.fixed.staff_flash", "anilist"),
      entry("changelog.4_1_0.fixed.detail_paging", "anilist"),
      entry("changelog.4_1_0.fixed.staff_profile", "anilist"),
      entry("changelog.4_1_0.fixed.staff_paging", "anilist"),
    ],
  },
  {
    version: "4.0.9",
    added: [
      entry("changelog.4_0_9.added.peers_modal", "torrents"),
      entry("changelog.4_0_9.added.peer_table", "torrents"),
      entry("changelog.4_0_9.added.peer_flags", "torrents"),
      entry("changelog.4_0_9.added.trackers_edit", "torrents"),
      entry("changelog.4_0_9.added.copy_app_link", "torrents"),
      entry("changelog.4_0_9.added.queue_order", "torrents"),
    ],
    changed: [
      entry("changelog.4_0_9.changed.engine", "torrents"),
      entry("changelog.4_0_9.changed.limits_button", "torrents"),
      entry("changelog.4_0_9.changed.parse_cache", "player"),
    ],
    fixed: [
      entry("changelog.4_0_9.fixed.tracker_rewrite", "torrents"),
      entry("changelog.4_0_9.fixed.list_refresh", "torrents"),
      entry("changelog.4_0_9.fixed.sequential_toggle", "torrents"),
      entry("changelog.4_0_9.fixed.queue_move", "torrents"),
      entry("changelog.4_0_9.fixed.cover_fallback", "collection"),
    ],
  },
  {
    version: "4.0.8",
    added: [],
    changed: [],
    fixed: [
      entry("changelog.4_0_8.fixed.covers_build", "collection"),
      entry("changelog.4_0_8.fixed.open_local", "collection"),
    ],
  },
  {
    version: "4.0.7",
    added: [],
    changed: [],
    fixed: [
      entry("changelog.4_0_7.fixed.titlebar_startup", "app"),
      entry("changelog.4_0_7.fixed.changelog_latest", "settings"),
    ],
  },
  {
    version: "4.0.6",
    added: [
      entry("changelog.4_0_6.added.custom_titlebar", "app"),
      entry("changelog.4_0_6.added.statusbar_toggle", "app"),
      entry("changelog.4_0_6.added.rounded_corners", "app"),
      entry("changelog.4_0_6.added.window_effects", "app"),
      entry("changelog.4_0_6.added.new_themes", "settings"),
      entry("changelog.4_0_6.added.platform_themes", "settings"),
      entry("changelog.4_0_6.added.yorha_grid", "settings"),
      entry("changelog.4_0_6.added.theme_editor_palette", "settings"),
      entry("changelog.4_0_6.added.observer_mascot", "search"),
      entry("changelog.4_0_6.added.dither_ascii", "search"),
      entry("changelog.4_0_6.added.dither_violet", "search"),
    ],
    changed: [entry("changelog.4_0_6.changed.theme_tokens", "settings")],
    fixed: [
      entry("changelog.4_0_6.fixed.grouped_dedupe", "anilist"),
      entry("changelog.4_0_6.fixed.theme_contrast", "settings"),
      entry("changelog.4_0_6.fixed.theme_palette_build", "settings"),
    ],
  },
  {
    version: "4.0.5",
    added: [
      entry("changelog.4_0_5.added.list_sort_keys", "anilist"),
      entry("changelog.4_0_5.added.grouped_lists", "anilist"),
      entry("changelog.4_0_5.added.all_tab", "anilist"),
      entry("changelog.4_0_5.added.aired_badge", "anilist"),
      entry("changelog.4_0_5.added.friend_view", "anilist"),
      entry("changelog.4_0_5.added.card_dates", "anilist"),
      entry("changelog.4_0_5.added.share_links", "collection"),
      entry("changelog.4_0_5.added.paste_anywhere", "app"),
      entry("changelog.4_0_5.added.paste_magnet", "torrents"),
      entry("changelog.4_0_5.added.paste_anilist_url", "anilist"),
    ],
    changed: [
      entry("changelog.4_0_5.changed.sort_select", "anilist"),
      entry("changelog.4_0_5.changed.continue_removed", "collection"),
      entry("changelog.4_0_5.changed.public_add", "collection"),
      entry("changelog.4_0_5.changed.relative_times", "app"),
    ],
    fixed: [
      entry("changelog.4_0_5.fixed.unified_index", "search"),
      entry("changelog.4_0_5.fixed.dither_stale", "search"),
      entry("changelog.4_0_5.fixed.import_loader", "collection"),
    ],
  },
  {
    version: "4.0.4",
    added: [entry("changelog.4_0_4.added.friend_scores", "anilist")],
    changed: [
      entry("changelog.4_0_4.changed.friends_modal", "anilist"),
      entry("changelog.4_0_4.changed.friend_scores_swatch", "anilist"),
      entry("changelog.4_0_4.changed.parallax_removed", "search"),
    ],
    fixed: [
      entry("changelog.4_0_4.fixed.youtube_build", "anilist"),
      entry("changelog.4_0_4.fixed.character_duplicate_key", "anilist"),
    ],
  },
  {
    version: "4.0.3",
    added: [
      entry("changelog.4_0_3.added.torrent_links", "torrents"),
      entry("changelog.4_0_3.added.link_paste", "app"),
      entry("changelog.4_0_3.added.friend_lists", "anilist"),
      entry("changelog.4_0_3.added.continue_row", "collection"),
      entry("changelog.4_0_3.added.credits_seasons", "collection"),
      entry("changelog.4_0_3.added.diagnostics", "torrents"),
      entry("changelog.4_0_3.added.bulk_actions", "torrents"),
      entry("changelog.4_0_3.added.torrent_network", "settings"),
      entry("changelog.4_0_3.added.media_panel", "settings"),
      entry("changelog.4_0_3.added.did_you_mean", "search"),
      entry("changelog.4_0_3.added.queue_retry", "player"),
    ],
    changed: [
      entry("changelog.4_0_3.changed.torrent_notify", "torrents"),
      entry("changelog.4_0_3.changed.root_sizes", "player"),
      entry("changelog.4_0_3.changed.sqlite_jump", "settings"),
    ],
    fixed: [
      entry("changelog.4_0_3.fixed.anime_link_tab", "anilist"),
      entry("changelog.4_0_3.fixed.fav_errors", "anilist"),
    ],
  },
  {
    version: "4.0.2",
    added: [],
    changed: [entry("changelog.4_0_2.changed.cover_thumbs", "collection")],
    fixed: [],
  },
  {
    version: "4.0.1",
    added: [],
    changed: [
      entry("changelog.4_0_1.changed.radio_nav", "search"),
      entry("changelog.4_0_1.changed.tag_docs", "collection"),
    ],
    fixed: [entry("changelog.4_0_1.fixed.color_popup", "app")],
  },
  {
    version: "4.0.0",
    added: [
      entry("changelog.4_0_0.added.modern_tab", "search"),
      entry("changelog.4_0_0.added.dither_presets", "search"),
      entry("changelog.4_0_0.added.wallpaper_fx", "search"),
      entry("changelog.4_0_0.added.spotlight", "anilist"),
      entry("changelog.4_0_0.added.random_menu", "collection"),
      entry("changelog.4_0_0.added.random_filters", "anilist"),
      entry("changelog.4_0_0.added.deeplinks", "app"),
      entry("changelog.4_0_0.added.release_dates", "collection"),
      entry("changelog.4_0_0.added.tag_ranges", "collection"),
      entry("changelog.4_0_0.added.franchise", "anilist"),
      entry("changelog.4_0_0.added.fav_people", "anilist"),
      entry("changelog.4_0_0.added.bilingual_labels", "collection"),
      entry("changelog.4_0_0.added.descriptions", "collection"),
      entry("changelog.4_0_0.added.filmstrip", "collection"),
      entry("changelog.4_0_0.added.fonts", "settings"),
      entry("changelog.4_0_0.added.sqlite_editor", "settings"),
      entry("changelog.4_0_0.added.autocomplete", "search"),
      entry("changelog.4_0_0.added.host_stats", "app"),
    ],
    changed: [
      entry("changelog.4_0_0.changed.tag_syntax", "collection"),
      entry("changelog.4_0_0.changed.anilist_tags", "collection"),
      entry("changelog.4_0_0.changed.jobcenter", "app"),
      entry("changelog.4_0_0.changed.semantic", "search"),
      entry("changelog.4_0_0.changed.gif", "search"),
      entry("changelog.4_0_0.changed.videoplayer", "app"),
      entry("changelog.4_0_0.changed.status_ui", "collection"),
      entry("changelog.4_0_0.changed.squares", "anilist"),
      entry("changelog.4_0_0.changed.tmdb_key", "settings"),
      entry("changelog.4_0_0.changed.list_rows", "collection"),
      entry("changelog.4_0_0.changed.autopause", "torrents"),
      entry("changelog.4_0_0.changed.hints", "app"),
      entry("changelog.4_0_0.changed.plurals_time", "app"),
    ],
    fixed: [
      entry("changelog.4_0_0.fixed.crash", "player"),
      entry("changelog.4_0_0.fixed.fresh_images", "app"),
      entry("changelog.4_0_0.fixed.status_order", "collection"),
      entry("changelog.4_0_0.fixed.files", "torrents"),
      entry("changelog.4_0_0.fixed.quickadd", "collection"),
      entry("changelog.4_0_0.fixed.refresh_touch", "collection"),
      entry("changelog.4_0_0.fixed.tmdb_covers", "anilist"),
    ],
  },
  {
    version: "3.2.0",
    added: [
      entry("changelog.3_2_0.added.upscale_cascade", "upscale"),
      entry("changelog.3_2_0.added.upscale_preview", "upscale"),
      entry("changelog.3_2_0.added.upscale_realcugan", "upscale"),
      entry("changelog.3_2_0.added.upscale_suggest", "upscale"),
      entry("changelog.3_2_0.added.upscale_codec", "upscale"),
      entry("changelog.3_2_0.added.upscale_rife", "upscale"),
      entry("changelog.3_2_0.added.upscale_temporal", "upscale"),
      entry("changelog.3_2_0.added.upscale_eta", "upscale"),
      entry("changelog.3_2_0.added.stills", "collection"),
      entry("changelog.3_2_0.added.trailer", "collection"),
      entry("changelog.3_2_0.added.media_db", "collection"),
      entry("changelog.3_2_0.added.jobcenter", "app"),
      entry("changelog.3_2_0.added.queue", "player"),
      entry("changelog.3_2_0.added.scan_task", "player"),
      entry("changelog.3_2_0.added.folder_resize", "player"),
      entry("changelog.3_2_0.added.torrent_states", "torrents"),
      entry("changelog.3_2_0.added.chips", "torrents"),
      entry("changelog.3_2_0.added.bridge", "anilist"),
      entry("changelog.3_2_0.added.prefetch_resume", "anilist"),
      entry("changelog.3_2_0.added.summary", "settings"),
      entry("changelog.3_2_0.added.changelog_tab", "settings"),
      entry("changelog.3_2_0.added.import_modes", "anilist"),
      entry("changelog.3_2_0.added.friends_activity", "anilist"),
      entry("changelog.3_2_0.added.favorites", "collection"),
      entry("changelog.3_2_0.added.proxies", "torrents"),
      entry("changelog.3_2_0.added.notifications_lists", "anilist"),
      entry("changelog.3_2_0.added.sqlite_views", "settings"),
      entry("changelog.3_2_0.added.search_tags", "collection"),
      entry("changelog.3_2_0.added.backfill", "settings"),
      entry("changelog.3_2_0.added.github", "app"),
    ],
    changed: [
      entry("changelog.3_2_0.changed.settings_layout", "settings"),
      entry("changelog.3_2_0.changed.toasts", "app"),
      entry("changelog.3_2_0.changed.shikimori", "app"),
      entry("changelog.3_2_0.changed.vault", "app"),
      entry("changelog.3_2_0.changed.duplicates", "collection"),
      entry("changelog.3_2_0.changed.activity_button", "anilist"),
      entry("changelog.3_2_0.changed.anilist_tabs", "anilist"),
    ],
    fixed: [
      entry("changelog.3_2_0.fixed.fts", "collection"),
      entry("changelog.3_2_0.fixed.activity_modal", "anilist"),
      entry("changelog.3_2_0.fixed.eye", "torrents"),
      entry("changelog.3_2_0.fixed.lost_update", "collection"),
      entry("changelog.3_2_0.fixed.updated_at", "collection"),
      entry("changelog.3_2_0.fixed.cloudflare", "torrents"),
      entry("changelog.3_2_0.fixed.search_hang", "torrents"),
    ],
  },
];
