import { DEFAULT_TAG_TOLERANCES } from "@/config/search/tolerance.config";
import type { SettingsDefaults, WallpaperDisplayFilters, WallpaperShadow } from "@/types/settings";

export const DEFAULT_WALLPAPER_FILTERS: WallpaperDisplayFilters = {
  brightness: 75,
  contrast: 100,
  saturate: 100,
  blur: 0,
  opacity: 100,
};

export const DEFAULT_WALLPAPER_SHADOW: WallpaperShadow = {
  sides: { top: false, right: false, bottom: false, left: false },
  intensity: 50,
  color: "#000000",
  length: 8,
  softness: 40,
};

export const DEFAULT_SETTINGS: SettingsDefaults = {
  anilistMaxPages: 3,
  collectionGroupHeaderStyle: "torrent",
  limits: { download: null, upload: null },
  pageSize: 40,
  anilistReleaseNotifications: true,
  notifyNewEpisodes: true,
  notifyStatusChanges: true,
  anilistPollIntervalMin: 30,
  anilistNotifyLists: null,
  anilistListSort: { key: "title", dir: "asc" },
  anilistGroupByStatus: false,
  anilistCollapsedLists: [],
  anilistDisplayMode: "pagination",
  audioExtensions: ["mp3", "flac", "aac", "ogg", "wav", "opus", "m4a", "wma"],
  buttonPressEffect: true,
  animateCounters: false,
  customScrollbar: true,
  customTitleBarEnabled: false,
  defaultSearchSource: "erai-raws",
  disablePersistence: false,
  enable3dBorders: true,
  enableAnimations: false,
  enableUpnp: true,
  fastresumeEnabled: true,
  fileOrder: "list",
  ffmpegSource: "essentials",
  hiddenPlayerFolders: [],
  hiddenPlayerTorrents: [],
  httpApiPort: 11200,
  ipv4Only: false,
  listenPort: 0,
  modalAnimation: false,
  modalBackdropOpacity: 50,
  notificationsEnabled: true,
  notifyOnComplete: true,
  notifyOnError: true,
  parseTitles: false,
  peerConnectTimeout: 10,
  peerReadWriteTimeout: 30,
  resultsPerPage: 20,
  retroStyle: "classic",
  roundedWindowCorners: false,
  windowEffect: "none",
  windowTintOpacity: null,
  savedFolderPaths: [],
  playerFolderHeights: {} as Record<string, number>,
  searchHistoryMaxItems: 100,
  searchMascotEnabled: false,
  autocompleteMode: "both",
  anilistSuggestionBoost: "subtle",
  showTrackFiles: "hide",
  sqliteBrowserEnabled: false,
  sqliteShowImages: false,
  statusBarEnabled: true,
  minimizeToTray: false,
  subtitleExtensions: ["srt", "ass", "ssa", "vtt", "sub", "idx", "sup", "pgs"],
  uiDensity: "comfortable",
  videoExtensions: [
    "mp4",
    "mkv",
    "avi",
    "mov",
    "webm",
    "flv",
    "wmv",
    "m4v",
    "mpg",
    "mpeg",
    "ts",
    "m2ts",
    "ogv",
    "3gp",
  ],
  visibleSources: ["erai-raws", "rutracker", "nyaa", "nekobt"],
  searchProxyUrls: {} as Record<string, string>,
  tmdbKeySet: false,
  tmdbPendingKey: null as string | null,
  tmdbProxyUrl: null as string | null,
  anilistProxyUrl: null as string | null,
  torrentProxyUrl: null as string | null,
  collectionTabEnabled: true,
  anilistTabEnabled: true,
  searchTabEnabled: true,
  torrentTabEnabled: true,
  playerTabEnabled: true,
  searchSymSpellEnabled: true,
  searchIntentEnabled: true,
  tagTolerances: { ...DEFAULT_TAG_TOLERANCES },
  searchType: "default",
  selectedDitherId: null as string | null,
  appFont: null as string | null,
  wallpaperFilters: { ...DEFAULT_WALLPAPER_FILTERS },
  wallpaperShadow: { ...DEFAULT_WALLPAPER_SHADOW },
  wallpaperScanlines: false,
  searchShadow: { ...DEFAULT_WALLPAPER_SHADOW },
  screenshotDir: null as string | null,
  screenshotFormat: "png",
  screenshotOpenFolder: true,
  yorhaScanlinesEnabled: true,
};
