import type { TranslationKey } from "@/types/i18n";
import type { ThemeColorKey, ThemeDefinition, ThemeOverrideKey } from "@/types/theme";

/**
 * Platform identities first, in the order a user would expect to browse them: Windows oldest to
 * newest, then Google and Apple. The settings grid renders `THEMES` in array order, and `win95`
 * stays first because it is the default theme.
 */
export const THEMES: ThemeDefinition[] = [
  {
    colors: {
      autocomplete: "#808080",
      background: "#222222",
      destructive: "#800000",
      field: "#ffffff",
      highlight: "#0000ff",
      linkHover: "#5c0000",
      muted: "#808080",
      primary: "#c0c0c0",
      secondary: "#000080",
      success: "#008000",
      surface: "#d0d0d0",
      text: "#000000",
      winHighlight: "#ffffff",
      winShadow: "#808080",
    },
    label: "Windows 95",
    name: "win95",
  },
  {
    colors: {
      autocomplete: "#b8b8b8",
      background: "#3a6ea5",
      destructive: "#cc0000",
      field: "#ffffff",
      highlight: "#1060c8",
      linkHover: "#0000ee",
      muted: "#8c8c8c",
      primary: "#ece9d8",
      secondary: "#0a246a",
      success: "#008000",
      surface: "#f0efe7",
      text: "#000000",
      winHighlight: "#ffffff",
      winShadow: "#999999",
    },
    label: "Windows 2000",
    name: "win2000",
  },
  {
    bevel: "raised",
    colors: {
      autocomplete: "#8a8778",
      background: "#3c7dba",
      destructive: "#cc0000",
      field: "#ffffff",
      highlight: "#316ac5",
      linkHover: "#af2c00",
      muted: "#6e6a5e",
      primary: "#ece9d8",
      secondary: "#0054e3",
      success: "#008000",
      surface: "#ddd8c9",
      text: "#000000",
      winHighlight: "#ffffff",
      winShadow: "#aca899",
    },
    fontFamily: "Tahoma",
    label: "Windows XP",
    name: "xp",
    radius: "frame",
    titlebarGradient: { from: "#3d8bef", to: "#0054e3" },
  },
  {
    bevel: "flat",
    colors: {
      autocomplete: "#7c93aa",
      background: "#205a8c",
      destructive: "#c42b1c",
      field: "#ffffff",
      highlight: "#0066cc",
      linkHover: "#26608b",
      muted: "#5f7285",
      primary: "#dfe9f5",
      secondary: "#0054a6",
      success: "#1e8e1e",
      surface: "#c9d9ea",
      text: "#0a0a0a",
      winHighlight: "#ffffff",
      winShadow: "#8fa6bc",
    },
    fontFamily: "Segoe UI",
    label: "Windows 7",
    name: "win7",
    radius: "frame",
    titlebarGradient: { from: "#f2f7fc", to: "#a6c1de" },
  },
  {
    bevel: "flat",
    colors: {
      autocomplete: "#6b6b6b",
      background: "#0e2c4e",
      destructive: "#c42b1c",
      field: "#ffffff",
      highlight: "#0067c0",
      linkHover: "#2b6d8f",
      muted: "#5c5c5c",
      primary: "#f3f3f3",
      secondary: "#0067c0",
      success: "#0f7b0f",
      surface: "#e7e7e7",
      text: "#1a1a1a",
      winHighlight: "#ffffff",
      winShadow: "#c8c8c8",
    },
    fontFamily: "Segoe UI Variable, Segoe UI",
    label: "Windows 11",
    name: "win11",
    radius: "all",
  },
  {
    bevel: "flat",
    colors: {
      autocomplete: "#80868b",
      background: "#202124",
      destructive: "#b3261e",
      field: "#ffffff",
      highlight: "#1a73e8",
      linkHover: "#8f2018",
      muted: "#5f6368",
      primary: "#f8f9fa",
      secondary: "#1967d2",
      // Green 700, not the brand 600: the brighter green only reaches 4.21 on a white face.
      success: "#188038",
      surface: "#e8eaed",
      text: "#202124",
      winHighlight: "#ffffff",
      winShadow: "#bdc1c6",
    },
    fontFamily: "Roboto",
    label: "Google",
    name: "google",
    radius: "all",
  },
  {
    bevel: "flat",
    colors: {
      autocomplete: "#8e8e93",
      background: "#1d1d1f",
      destructive: "#d70015",
      field: "#ffffff",
      highlight: "#0071e3",
      // A darker blue rather than the system red: a hovered link still has to be readable, and
      // #ff3b30 only reaches 3.55 on this face.
      linkHover: "#004499",
      muted: "#6e6e73",
      primary: "#f5f5f7",
      secondary: "#0066cc",
      success: "#1e7a33",
      surface: "#e8e8ed",
      text: "#1d1d1f",
      winHighlight: "#ffffff",
      winShadow: "#c7c7cc",
    },
    // San Francisco is not redistributable, so the theme ships Inter - the closest open equivalent -
    // instead of naming a family we cannot bundle.
    fontFamily: "Inter",
    label: "Apple",
    name: "apple",
    radius: "all",
  },
  {
    colors: {
      autocomplete: "#6e6e6e",
      background: "#1a1a1a",
      destructive: "#767676",
      field: "#ffffff",
      highlight: "#4a4a4a",
      linkHover: "#000000",
      muted: "#808080",
      primary: "#d6d6d6",
      secondary: "#4a4a4a",
      success: "#a0a0a0",
      surface: "#c4c4c4",
      text: "#1a1a1a",
      winHighlight: "#ffffff",
      winShadow: "#808080",
    },
    label: "Monochrome",
    name: "mono",
    overrides: { favGold: "#8a8a8a", torrentIdle: "#c4c4c4", torrentSeeding: "#1e1e1e" },
  },
  {
    colors: {
      autocomplete: "#c4c4c4",
      background: "#1a1a1a",
      destructive: "#ff723e",
      field: "#ffffff",
      highlight: "#3c9a94",
      linkHover: "#296561",
      muted: "#9b9b9b",
      primary: "#d8d8d8",
      secondary: "#207874",
      success: "#2f8f5b",
      surface: "#e8e8e8",
      text: "#000000",
      winHighlight: "#efefef",
      winShadow: "#8a8a8a",
    },
    fontFamily: "Perfect DOS VGA 437",
    label: "Retroism",
    name: "retroism",
  },
  {
    colors: {
      autocomplete: "#b8b3a0",
      background: "#1a1a1a",
      destructive: "#cd664d",
      field: "#ffffff",
      highlight: "#a0522d",
      linkHover: "#614734",
      muted: "#979381",
      primary: "#dad4bb",
      secondary: "#57544a",
      success: "#7f9a6b",
      surface: "#c8c3ae",
      text: "#000000",
      winHighlight: "#e5dfc8",
      winShadow: "#8f8b7a",
    },
    label: "YoRHa",
    name: "yorha",
    fontFamily: '"IBM Plex Sans", "MS Sans Serif", "Microsoft Sans Serif", "Segoe UI", system-ui',
  },
  {
    colors: {
      autocomplete: "#d4aecf",
      background: "#1a1a1a",
      destructive: "#d43e6a",
      field: "#ffffff",
      highlight: "#c950bb",
      linkHover: "#8a4275",
      muted: "#b08aaa",
      primary: "#f4c9ef",
      secondary: "#c950bb",
      success: "#6fae7c",
      surface: "#f7d5f3",
      text: "#000000",
      winHighlight: "#fadef6",
      winShadow: "#a482a0",
    },
    label: "Cherry",
    name: "cherry",
  },
  {
    colors: {
      autocomplete: "#a9b3d1",
      background: "#1a1a1a",
      destructive: "#d45e3e",
      field: "#ffffff",
      highlight: "#3e7c99",
      linkHover: "#2e5463",
      muted: "#8a94b0",
      primary: "#bac4e6",
      secondary: "#3e7c99",
      success: "#5f9e78",
      surface: "#ccd3ee",
      text: "#000000",
      winHighlight: "#d5dbf2",
      winShadow: "#7c86a4",
    },
    label: "Indigo",
    name: "indigo",
  },
  {
    colors: {
      autocomplete: "#a3c4ad",
      background: "#1a1a1a",
      destructive: "#d4663e",
      field: "#ffffff",
      highlight: "#2e7a36",
      linkHover: "#285730",
      muted: "#8ab094",
      primary: "#bae6c5",
      secondary: "#3e9949",
      success: "#3e9949",
      surface: "#ccefd5",
      text: "#000000",
      winHighlight: "#d5f2dc",
      winShadow: "#7a9e85",
    },
    label: "Gleep",
    name: "gleep",
  },
  {
    colors: {
      autocomplete: "#9aa3c8",
      background: "#282a36",
      destructive: "#ff5555",
      field: "#313341",
      highlight: "#8be9fd",
      linkHover: "#ffbfe4",
      muted: "#6272a4",
      primary: "#44475a",
      secondary: "#bd93f9",
      success: "#50fa7b",
      surface: "#555770",
      text: "#f8f8f2",
      winHighlight: "#686b80",
      winShadow: "#343746",
    },
    label: "Dracula",
    name: "dracula",
  },
  {
    colors: {
      autocomplete: "#8f9bb3",
      background: "#2e3440",
      destructive: "#bf616a",
      field: "#2e3440",
      highlight: "#81a1c1",
      linkHover: "#afc0d6",
      muted: "#616e88",
      primary: "#3b4252",
      secondary: "#88c0d0",
      success: "#a3be8c",
      surface: "#434c5e",
      text: "#eceff4",
      winHighlight: "#5e6a84",
      winShadow: "#2b303c",
    },
    label: "Nord",
    name: "nord",
  },
  {
    colors: {
      autocomplete: "#828a99",
      background: "#1e2127",
      destructive: "#e06c75",
      field: "#21252b",
      highlight: "#c678dd",
      linkHover: "#61afef",
      muted: "#5c6370",
      primary: "#282c34",
      secondary: "#61afef",
      success: "#98c379",
      surface: "#353b45",
      text: "#abb2bf",
      winHighlight: "#4b5263",
      winShadow: "#1b1f24",
    },
    label: "One Dark",
    name: "one-dark",
  },
  {
    colors: {
      autocomplete: "#b0a99a",
      background: "#282828",
      destructive: "#cc241d",
      field: "#282828",
      highlight: "#8ec07c",
      linkHover: "#e2b65f",
      muted: "#928374",
      primary: "#3c3836",
      secondary: "#d79921",
      success: "#98971a",
      surface: "#504945",
      text: "#ebdbb2",
      winHighlight: "#665c54",
      winShadow: "#2c2926",
    },
    label: "Gruvbox Dark",
    name: "gruvbox-dark",
  },
  {
    colors: {
      autocomplete: "#9e9e9e",
      background: "#000000",
      destructive: "#cf6679",
      field: "#0a0a0a",
      highlight: "#03dac6",
      linkHover: "#bb86fc",
      muted: "#757575",
      primary: "#121212",
      secondary: "#bb86fc",
      success: "#4caf50",
      surface: "#1e1e1e",
      text: "#ffffff",
      winHighlight: "#2c2c2c",
      winShadow: "#000000",
    },
    label: "Amoled",
    name: "amoled",
  },
  {
    colors: {
      autocomplete: "#a5a9bb",
      background: "#eff1f5",
      destructive: "#d20f39",
      field: "#ffffff",
      highlight: "#1e66f5",
      linkHover: "#7d34dc",
      muted: "#9ca0b0",
      primary: "#e6e9ef",
      secondary: "#8839ef",
      success: "#40a02b",
      surface: "#dce0e8",
      text: "#4c4f69",
      winHighlight: "#f5f6f9",
      winShadow: "#bcc0cc",
    },
    label: "Catppuccin Latte",
    name: "catppuccin-latte",
  },
  {
    colors: {
      autocomplete: "#00b32d",
      background: "#0c0c0c",
      destructive: "#ff0041",
      field: "#0c0c0c",
      highlight: "#ffffff",
      linkHover: "#33ff66",
      muted: "#005a00",
      primary: "#1a1a1a",
      secondary: "#00ff41",
      success: "#00ff41",
      surface: "#242424",
      text: "#00ff41",
      winHighlight: "#333333",
      winShadow: "#000000",
    },
    fontFamily: "Perfect DOS VGA 437, monospace",
    label: "Terminal",
    name: "terminal",
  },
  {
    colors: {
      autocomplete: "#7b88b8",
      background: "#16161e",
      destructive: "#f7768e",
      field: "#1a1b26",
      highlight: "#bb9af7",
      linkHover: "#7dcfff",
      muted: "#565f89",
      primary: "#24283b",
      secondary: "#7aa2f7",
      success: "#9ece6a",
      surface: "#292e42",
      text: "#c0caf5",
      winHighlight: "#3b4261",
      winShadow: "#1a1b26",
    },
    label: "Tokyo Night",
    name: "tokyo-night",
  },
  {
    colors: {
      autocomplete: "#9399b2",
      background: "#11111b",
      destructive: "#f38ba8",
      field: "#1e1e2e",
      highlight: "#89b4fa",
      linkHover: "#89dceb",
      muted: "#7f849c",
      primary: "#313244",
      secondary: "#cba6f7",
      success: "#a6e3a1",
      surface: "#45475a",
      text: "#cdd6f4",
      winHighlight: "#585b70",
      winShadow: "#232334",
    },
    label: "Catppuccin Mocha",
    name: "catppuccin-mocha",
  },
  {
    colors: {
      autocomplete: "#b3ab93",
      background: "#fdf6e3",
      destructive: "#dc322f",
      field: "#fdf6e3",
      highlight: "#2aa198",
      linkHover: "#ad2c6b",
      muted: "#93a1a1",
      primary: "#eee8d5",
      secondary: "#268bd2",
      success: "#859900",
      surface: "#e4ddc6",
      text: "#073642",
      winHighlight: "#ffffff",
      winShadow: "#c9bfa6",
    },
    label: "Solarized Light",
    name: "solarized-light",
  },
  {
    colors: {
      autocomplete: "#c6d94a",
      background: "#0f380f",
      destructive: "#8b2020",
      field: "#cfe08f",
      highlight: "#8bac0f",
      linkHover: "#0f380f",
      muted: "#4a7a2a",
      primary: "#9bbc0f",
      secondary: "#306230",
      success: "#8bac0f",
      surface: "#8bac0f",
      text: "#0f380f",
      winHighlight: "#cfe08f",
      winShadow: "#6a8a0a",
    },
    fontFamily: "Perfect DOS VGA 437, monospace",
    label: "Game Boy",
    name: "game-boy",
    overrides: { torrentDone: "#0f380f" },
  },
];

/** CSS variable written for each `ThemeDefinition.overrides` key. */
export const THEME_OVERRIDE_VARS: Record<ThemeOverrideKey, string> = {
  favGold: "--color-fav-gold",
  graphDefault: "--color-graph-default",
  graphLight: "--color-graph-light",
  graphPale: "--color-graph-pale",
  graphPrequel: "--color-graph-prequel",
  graphSequel: "--color-graph-sequel",
  graphSide: "--color-graph-side",
  graphSpinoff: "--color-graph-spinoff",
  torrentDownloading: "--color-torrent-downloading",
  torrentDone: "--color-torrent-done",
  torrentError: "--color-torrent-error",
  torrentIdle: "--color-torrent-idle",
  torrentSeeding: "--color-torrent-seeding",
};

/**
 * Themes built from a four-shade palette cannot spread four accents apart without
 * leaving the palette, so the accent-distinctness check steps aside for them.
 * The status-colour check still applies: Game Boy separates `done` with an override.
 */
export const THEME_ACCENT_EXEMPT = ["game-boy"];

export const THEME_COLOR_KEYS: {
  key: ThemeColorKey;
  label: TranslationKey;
}[] = [
  { key: "background", label: "settings.theme.color.background" },
  { key: "primary", label: "settings.theme.color.primary" },
  { key: "secondary", label: "settings.theme.color.secondary" },
  { key: "text", label: "settings.theme.color.text" },
  { key: "muted", label: "settings.theme.color.muted" },
  { key: "autocomplete", label: "settings.theme.color.autocomplete" },
  { key: "highlight", label: "settings.theme.color.highlight" },
  { key: "linkHover", label: "settings.theme.color.link.hover" },
  { key: "destructive", label: "settings.theme.color.destructive" },
  { key: "success", label: "settings.theme.color.success" },
  { key: "surface", label: "settings.theme.color.surface" },
  { key: "field", label: "settings.theme.color.field" },
  { key: "winHighlight", label: "settings.theme.color.win.highlight" },
  { key: "winShadow", label: "settings.theme.color.win.shadow" },
];
