import type { TranslationKey } from "@/types/i18n";
import type { ThemeColorKey, ThemeDefinition, ThemeOverrideKey } from "@/types/theme";

export const DEFAULT_THEME_COLORS: ThemeDefinition["colors"] & {
  autocomplete: string;
  autocompleteOpacity: number;
} = {
  autocomplete: "#808080",
  autocompleteOpacity: 0.6,
  background: "#222222",
  destructive: "#800000",
  field: "#ffffff",
  highlight: "#0000ff",
  linkHover: "#5c0000",
  muted: "#808080",
  primary: "#c0c0c0",
  secondary: "#000080",
  success: "#008000",
  surface: "#d0d0d0",
  text: "#000000",
  winHighlight: "#ffffff",
  winShadow: "#808080",
};

export const THEMES: ThemeDefinition[] = [
  {
    colors: {
      autocomplete: "#808080",
      background: "#222222",
      destructive: "#800000",
      field: "#ffffff",
      highlight: "#0000ff",
      linkHover: "#5c0000",
      muted: "#808080",
      primary: "#c0c0c0",
      secondary: "#000080",
      success: "#008000",
      surface: "#d0d0d0",
      text: "#000000",
      winHighlight: "#ffffff",
      winShadow: "#808080",
    },
    label: "Windows 95",
    name: "win95",
  },
  {
    bevel: "raised",
    colors: {
      autocomplete: "#8a8778",
      background: "#3c7dba",
      destructive: "#cc0000",
      field: "#ffffff",
      highlight: "#316ac5",
      linkHover: "#af2c00",
      muted: "#6e6a5e",
      primary: "#ece9d8",
      secondary: "#0054e3",
      success: "#008000",
      surface: "#ddd8c9",
      text: "#000000",
      winHighlight: "#ffffff",
      winShadow: "#aca899",
    },
    fontFamily: "Tahoma",
    label: "Windows XP",
    name: "xp",
    radius: "frame",
    titlebarGradient: { from: "#3d8bef", to: "#0054e3" },
  },
  {
    bevel: "flat",
    colors: {
      autocomplete: "#7c93aa",
      background: "#205a8c",
      destructive: "#c42b1c",
      field: "#ffffff",
      highlight: "#0066cc",
      linkHover: "#26608b",
      muted: "#5f7285",
      primary: "#dfe9f5",
      secondary: "#0054a6",
      success: "#1e8e1e",
      surface: "#c9d9ea",
      text: "#0a0a0a",
      winHighlight: "#ffffff",
      winShadow: "#8fa6bc",
    },
    fontFamily: "Segoe UI",
    label: "Windows 7",
    name: "win7",
    radius: "frame",
    titlebarGradient: { from: "#f2f7fc", to: "#a6c1de" },
  },
  {
    bevel: "flat",
    colors: {
      autocomplete: "#80868b",
      background: "#202124",
      destructive: "#b3261e",
      field: "#ffffff",
      highlight: "#1a73e8",
      linkHover: "#8f2018",
      muted: "#5f6368",
      primary: "#f8f9fa",
      secondary: "#1967d2",
      success: "#188038",
      surface: "#e8eaed",
      text: "#202124",
      winHighlight: "#ffffff",
      winShadow: "#bdc1c6",
    },
    fontFamily: "Roboto",
    label: "Google",
    name: "google",
    radius: "all",
  },
  {
    bevel: "flat",
    colors: {
      autocomplete: "#8e8e93",
      background: "#1d1d1f",
      destructive: "#d70015",
      field: "#ffffff",
      highlight: "#0071e3",
      linkHover: "#004499",
      muted: "#6e6e73",
      primary: "#f5f5f7",
      secondary: "#0066cc",
      success: "#1e7a33",
      surface: "#e8e8ed",
      text: "#1d1d1f",
      winHighlight: "#ffffff",
      winShadow: "#9aa0b0",
    },
    fontFamily: "Inter",
    label: "Apple",
    name: "apple",
    radius: "all",
    titlebarGradient: { from: "#e6eefb", to: "#a9c4e8" },
  },
  {
    colors: {
      autocomplete: "#6e6e6e",
      background: "#1a1a1a",
      destructive: "#767676",
      field: "#ffffff",
      highlight: "#4a4a4a",
      linkHover: "#000000",
      muted: "#808080",
      primary: "#d6d6d6",
      secondary: "#4a4a4a",
      success: "#a0a0a0",
      surface: "#c4c4c4",
      text: "#1a1a1a",
      winHighlight: "#ffffff",
      winShadow: "#808080",
    },
    label: "Monochrome",
    name: "mono",
    overrides: { favGold: "#8a8a8a", torrentIdle: "#c4c4c4", torrentSeeding: "#1e1e1e" },
    components: { cardMeta: "short" },
  },
  {
    colors: {
      autocomplete: "#c4c4c4",
      background: "#1a1a1a",
      destructive: "#ff723e",
      field: "#ffffff",
      highlight: "#3c9a94",
      linkHover: "#296561",
      muted: "#9b9b9b",
      primary: "#d8d8d8",
      secondary: "#207874",
      success: "#2f8f5b",
      surface: "#e8e8e8",
      text: "#000000",
      winHighlight: "#efefef",
      winShadow: "#8a8a8a",
    },
    fontFamily: "Perfect DOS VGA 437",
    label: "Retroism",
    name: "retroism",
  },
  {
    colors: {
      autocomplete: "#b8b3a0",
      background: "#1a1a1a",
      destructive: "#cd664d",
      field: "#ffffff",
      highlight: "#a0522d",
      linkHover: "#614734",
      muted: "#979381",
      primary: "#dad4bb",
      secondary: "#57544a",
      success: "#7f9a6b",
      surface: "#c8c3ae",
      text: "#000000",
      winHighlight: "#e5dfc8",
      winShadow: "#8f8b7a",
    },
    label: "YoRHa",
    name: "yorha",
    overlay: "grid",
    components: { titlebarArt: true },
    fontFamily: '"IBM Plex Sans", "MS Sans Serif", "Microsoft Sans Serif", "Segoe UI", system-ui',
  },
  {
    colors: {
      autocomplete: "#a3c4ad",
      background: "#1a1a1a",
      destructive: "#d4663e",
      field: "#ffffff",
      highlight: "#2e7a36",
      linkHover: "#285730",
      muted: "#8ab094",
      primary: "#bae6c5",
      secondary: "#3e9949",
      success: "#3e9949",
      surface: "#ccefd5",
      text: "#000000",
      winHighlight: "#d5f2dc",
      winShadow: "#7a9e85",
    },
    label: "Gleep",
    name: "gleep",
  },
  {
    colors: {
      autocomplete: "#b0a99a",
      background: "#282828",
      destructive: "#cc241d",
      field: "#282828",
      highlight: "#8ec07c",
      linkHover: "#e2b65f",
      muted: "#928374",
      primary: "#3c3836",
      secondary: "#d79921",
      success: "#98971a",
      surface: "#504945",
      text: "#ebdbb2",
      winHighlight: "#665c54",
      winShadow: "#2c2926",
    },
    label: "Gruvbox Dark",
    name: "gruvbox-dark",
  },
  {
    colors: {
      autocomplete: "#9e9e9e",
      background: "#000000",
      destructive: "#cf6679",
      field: "#0a0a0a",
      highlight: "#03dac6",
      linkHover: "#bb86fc",
      muted: "#757575",
      primary: "#121212",
      secondary: "#bb86fc",
      success: "#4caf50",
      surface: "#1e1e1e",
      text: "#ffffff",
      winHighlight: "#2c2c2c",
      winShadow: "#000000",
    },
    label: "Amoled",
    name: "amoled",
  },
  {
    colors: {
      autocomplete: "#00b32d",
      background: "#0c0c0c",
      destructive: "#ff0041",
      field: "#0c0c0c",
      highlight: "#ffffff",
      linkHover: "#33ff66",
      muted: "#005a00",
      primary: "#1a1a1a",
      secondary: "#00ff41",
      success: "#00ff41",
      surface: "#242424",
      text: "#00ff41",
      winHighlight: "#333333",
      winShadow: "#000000",
    },
    fontFamily: "Perfect DOS VGA 437, monospace",
    label: "Terminal",
    name: "terminal",
    overlay: "scanlines",
    components: { cardMeta: "short" },
  },
  {
    colors: {
      autocomplete: "#7b88b8",
      background: "#16161e",
      destructive: "#f7768e",
      field: "#1a1b26",
      highlight: "#bb9af7",
      linkHover: "#7dcfff",
      muted: "#565f89",
      primary: "#24283b",
      secondary: "#7aa2f7",
      success: "#9ece6a",
      surface: "#292e42",
      text: "#c0caf5",
      winHighlight: "#3b4261",
      winShadow: "#1a1b26",
    },
    label: "Tokyo Night",
    name: "tokyo-night",
  },
  {
    colors: {
      autocomplete: "#c6d94a",
      background: "#0f380f",
      destructive: "#8b2020",
      field: "#cfe08f",
      highlight: "#8bac0f",
      linkHover: "#0f380f",
      muted: "#4a7a2a",
      primary: "#9bbc0f",
      secondary: "#306230",
      success: "#8bac0f",
      surface: "#8bac0f",
      text: "#0f380f",
      winHighlight: "#cfe08f",
      winShadow: "#6a8a0a",
    },
    fontFamily: "Perfect DOS VGA 437, monospace",
    label: "Game Boy",
    name: "game-boy",
    overrides: { torrentDone: "#0f380f" },
  },
  {
    bevel: "flat",
    colors: {
      autocomplete: "#9fadbd",
      background: "#0b1622",
      destructive: "#f87171",
      field: "#0b1622",
      highlight: "#3db4f2",
      linkHover: "#7dd3fc",
      muted: "#9fadbd",
      primary: "#151f2e",
      secondary: "#3db4f2",
      success: "#4ade80",
      surface: "#1e2c3f",
      text: "#edf1f5",
      winHighlight: "#2e4257",
      winShadow: "#05090f",
    },
    fontFamily: "Roboto",
    label: "AniList",
    name: "anilist",
    overlay: "grid",
    components: { titlebarArt: true },
    radius: "all",
  },
];

export const THEME_OVERRIDE_VARS: Record<ThemeOverrideKey, string> = {
  favGold: "--color-fav-gold",
  graphDefault: "--color-graph-default",
  graphLight: "--color-graph-light",
  graphPale: "--color-graph-pale",
  graphPrequel: "--color-graph-prequel",
  graphSequel: "--color-graph-sequel",
  graphSide: "--color-graph-side",
  graphSpinoff: "--color-graph-spinoff",
  torrentDownloading: "--color-torrent-downloading",
  torrentDone: "--color-torrent-done",
  torrentError: "--color-torrent-error",
  torrentInitializing: "--color-torrent-initializing",
  torrentIdle: "--color-torrent-idle",
  torrentMissing: "--color-torrent-missing",
  torrentSeeding: "--color-torrent-seeding",
  progressMain: "--color-progress-main",
};

export const THEME_ACCENT_EXEMPT = ["game-boy"];

export const THEME_COLOR_KEYS: {
  key: ThemeColorKey;
  label: TranslationKey;
}[] = [
  { key: "background", label: "settings.theme.color.background" },
  { key: "primary", label: "settings.theme.color.primary" },
  { key: "secondary", label: "settings.theme.color.secondary" },
  { key: "text", label: "settings.theme.color.text" },
  { key: "muted", label: "settings.theme.color.muted" },
  { key: "autocomplete", label: "settings.theme.color.autocomplete" },
  { key: "highlight", label: "settings.theme.color.highlight" },
  { key: "linkHover", label: "settings.theme.color.link.hover" },
  { key: "destructive", label: "settings.theme.color.destructive" },
  { key: "success", label: "settings.theme.color.success" },
  { key: "surface", label: "settings.theme.color.surface" },
  { key: "field", label: "settings.theme.color.field" },
  { key: "winHighlight", label: "settings.theme.color.win.highlight" },
  { key: "winShadow", label: "settings.theme.color.win.shadow" },
];
