import { defineConfig } from "oxlint";
import core from "ultracite/oxlint/core";
import jsPlugins from "ultracite/oxlint/js-plugins";
import react from "ultracite/oxlint/react";
import tanstack from "ultracite/oxlint/tanstack";
import tanstackJsPlugins from "ultracite/oxlint/tanstack/js-plugins";

const selectedJsPluginNames = new Set(["react-doctor"]);
const selectedJsPluginRulePrefixes = new Set(["react-doctor"]);
const legacyRulesToDisable = [
  "func-style",
  "react/function-component-definition",
  "react-doctor/no-reset-all-state-on-prop-change",
  "react-doctor/react-compiler-no-manual-memoization",
  "react-doctor/prefer-useReducer",
  "react-doctor/no-giant-component",
  "react-doctor/js-combine-iterations",
  "react-doctor/js-set-map-lookups",
  "react-doctor/no-array-index-as-key",
  "react-doctor/prefer-module-scope-pure-function",
  "react-doctor/prefer-module-scope-static-value",
  "react-doctor/rerender-lazy-state-init",
  "react-doctor/no-chain-state-updates",
  "react-doctor/no-effect-chain",
  "react-doctor/no-pass-data-to-parent",
  "react-doctor/no-prop-callback-in-effect",
  "jsx-a11y/no-static-element-interactions",
  "jsx-a11y/click-events-have-key-events",
  "jsx-a11y/prefer-tag-over-role",
  "jsx-a11y/label-has-associated-control",
  "jsx-a11y/control-has-associated-label",
  "react/exhaustive-deps",
  "no-eq-null",
  "eqeqeq",
  "no-nested-ternary",
  "no-shadow",
  "no-empty",
  "no-empty-function",
  "no-plusplus",
  "no-array-sort",
  "no-array-for-each",
  "no-use-before-define",
  "no-alert",
  "no-bitwise",
  "no-negated-condition",
  "no-lonely-if",
  "no-duplicate-imports",
  "no-unsafe-return",
  "prefer-destructuring",
  "prefer-named-capture-group",
  "require-unicode-regexp",
  "sort-keys",
  "promise/prefer-await-to-then",
  "promise/prefer-await-to-callbacks",
  "promise/avoid-new",
  "typescript/consistent-return",
  "typescript/consistent-type-imports",
  "typescript/no-dynamic-delete",
  "typescript/no-explicit-any",
  "typescript/no-misused-promises",
  "typescript/no-non-null-assertion",
  "typescript/no-unnecessary-condition",
  "typescript/no-unsafe-call",
  "typescript/no-unsafe-member-access",
  "typescript/no-unsafe-return",
  "typescript/prefer-optional-chain",
  "typescript/array-type",
  "typescript/consistent-type-assertions",
  "typescript/consistent-type-definitions",
  "typescript/no-unsafe-argument",
  "typescript/no-unsafe-assignment",
  "typescript/no-unnecessary-type-assertion",
  "typescript/no-unnecessary-type-conversion",
  "typescript/no-unnecessary-type-parameters",
  "typescript/no-unnecessary-qualifier",
  "typescript/no-unnecessary-template-expression",
  "typescript/no-redundant-type-constituents",
  "typescript/no-confusing-void-expression",
  "typescript/require-await",
  "unicorn/consistent-function-scoping",
  "unicorn/no-array-reduce",
  "unicorn/no-array-sort",
  "unicorn/no-array-for-each",
  "unicorn/no-immediate-mutation",
  "unicorn/prefer-array-find",
  "unicorn/prefer-logical-operator-over-ternary",
  "unicorn/prefer-number-coercion",
  "unicorn/prefer-number-properties",
  "unicorn/prefer-string-replace-all",
  "unicorn/numeric-separators-style",
  "unicorn/prefer-ternary",
  "unicorn/prefer-add-event-listener",
  "unicorn/prefer-export-from",
  "unicorn/no-useless-undefined",
  "unicorn/no-useless-collection-argument",
  "unicorn/no-zero-fractions",
  "unicorn/no-nested-ternary",
  "unicorn/no-negated-condition",
  "unicorn/catch-error-name",
  "unicorn/no-lonely-if",
  "unicorn/empty-brace-spaces",
  "unicorn/filename-case",
  "unicorn/import-style",
  "unicorn/prefer-spread",
  "unicorn/prefer-array-some",
  "react/display-name",
  "react/no-object-type-as-default-prop",
  "react/jsx-no-useless-fragment",
  "react/jsx-pascal-case",
  "react/state-in-constructor",
  "react/no-set-state",
  "jsx-a11y/no-noninteractive-element-interactions",
  "react-doctor/no-flush-sync",
  "react-doctor/js-tosorted-immutable",
  "react-doctor/no-event-handler",
  "react-doctor/js-flatmap-filter",
  "react-doctor/client-localstorage-no-version",
  "react-doctor/prefer-use-effect-event",
  "react-doctor/only-export-components",
  "react-doctor/async-await-in-loop",
  "react-doctor/no-effect-with-fresh-deps",
  "promise/no-callback-in-promise",
  "promise/no-nesting",
  "import/first",
  "import/no-duplicates",
  "import/consistent-type-specifier-style",
  "oxc/branches-sharing-code",
  "oxc/no-accumulating-spread",
  "default-case",
  "no-await-in-loop",
  "no-promise-executor-return",
  "arrow-body-style",
  "object-shorthand",
  "prefer-regex-literals",
  "prefer-array-some",
  "no-unmodified-loop-condition",
  "require-await",
  "class-methods-use-this",
  "jsx-a11y/media-has-caption",
  "react/set-state-in-effect",
  "react/todo",
  "react/immutability",
  "react/globals",
  "react/preserve-manual-memoization",
  "react/no-deriving-state-in-effects",
  "react/purity",
  "react/incompatible-library",
  "react-doctor/no-adjust-state-on-prop-change",
] as const;

const selectedJsPlugins = {
  ...jsPlugins,
  jsPlugins: jsPlugins.jsPlugins?.filter((plugin) =>
    selectedJsPluginNames.has(typeof plugin === "string" ? plugin : plugin.name)
  ),
  overrides: jsPlugins.overrides?.map((override) => ({
    ...override,
    rules: Object.fromEntries(
      Object.entries(override.rules ?? {}).filter(([ruleName]) =>
        selectedJsPluginRulePrefixes.has(ruleName.split("/")[0] ?? ruleName)
      )
    ),
  })),
  rules: Object.fromEntries(
    Object.entries(jsPlugins.rules ?? {}).filter(([ruleName]) =>
      selectedJsPluginRulePrefixes.has(ruleName.split("/")[0] ?? ruleName)
    )
  ),
};

export default defineConfig({
  extends: [core, react, tanstack, selectedJsPlugins, tanstackJsPlugins],
  ignorePatterns: [...(core.ignorePatterns ?? []), "src-tauri/**", "md/**"],
  options: {
    typeAware: true,
    typeCheck: true,
  },
  rules: {
    complexity: "error",
    curly: "off",
    "no-else-return": "off",
    "typescript/await-thenable": "error",
    "typescript/consistent-return": "warn",
    "typescript/consistent-type-exports": "off",
    "typescript/dot-notation": "off",
    "typescript/no-array-delete": "off",
    "typescript/no-base-to-string": "off",
    "typescript/no-confusing-void-expression": "off",
    "typescript/no-deprecated": "off",
    "typescript/no-duplicate-type-constituents": "off",
    "typescript/no-floating-promises": "off",
    "typescript/no-for-in-array": "off",
    "typescript/no-implied-eval": "error",
    "typescript/no-meaningless-void-operator": "off",
    "typescript/no-misused-promises": "warn",
    "typescript/no-misused-spread": "off",
    "typescript/no-mixed-enums": "off",
    "typescript/no-redundant-type-constituents": "off",
    "typescript/no-unnecessary-boolean-literal-compare": "off",
    "typescript/no-unnecessary-condition": "error",
    "typescript/no-unnecessary-qualifier": "off",
    "typescript/no-unnecessary-template-expression": "off",
    "typescript/no-unnecessary-type-arguments": "off",
    "typescript/no-unnecessary-type-assertion": "off",
    "typescript/no-unnecessary-type-conversion": "off",
    "typescript/no-unnecessary-type-parameters": "off",
    "typescript/no-unsafe-argument": "off",
    "typescript/no-unsafe-assignment": "off",
    "typescript/no-unsafe-call": "error",
    "typescript/no-unsafe-enum-comparison": "off",
    "typescript/no-unsafe-member-access": "error",
    "typescript/no-unsafe-return": "error",
    "typescript/no-unsafe-type-assertion": "off",
    "typescript/no-unsafe-unary-minus": "off",
    "typescript/no-useless-default-assignment": "off",
    "typescript/non-nullable-type-assertion-style": "off",
    "typescript/only-throw-error": "off",
    "typescript/prefer-find": "off",
    "typescript/prefer-includes": "off",
    "typescript/prefer-nullish-coalescing": "off",
    "typescript/prefer-optional-chain": "error",
    "typescript/prefer-promise-reject-errors": "off",
    "typescript/prefer-readonly": "off",
    "typescript/prefer-readonly-parameter-types": "off",
    "typescript/prefer-reduce-type-parameter": "off",
    "typescript/prefer-regexp-exec": "off",
    "typescript/prefer-return-this-type": "off",
    "typescript/prefer-string-starts-ends-with": "off",
    "typescript/promise-function-async": "off",
    "typescript/related-getter-setter-pairs": "off",
    "typescript/require-array-sort-compare": "off",
    "typescript/require-await": "off",
    "typescript/restrict-plus-operands": "off",
    "typescript/restrict-template-expressions": "off",
    "typescript/return-await": "off",
    "typescript/strict-boolean-expressions": "off",
    "typescript/strict-void-return": "off",
    "typescript/switch-exhaustiveness-check": "off",
    "typescript/unbound-method": "off",
    "typescript/use-unknown-in-catch-callback-variable": "off",
    "unicorn/prefer-ternary": "off",
    "no-void": "error",
    ...Object.fromEntries(legacyRulesToDisable.map((rule) => [rule, "off"])),
  },
});
