import type { Locale } from "./i18n";
import type { AutocompleteMode } from "./search";

export type SettingsTab = "general" | "search" | "torrent" | "theme" | "sqlite" | "notifications";

export type FFMPEGStatus = "checking" | "ok" | "missing" | "downloading";

export type ScanType = { current: number; total: number } | null;

export interface SettingsStore {
  language: Locale;
  dlLimit: number | null;
  ulLimit: number | null;
  notificationsEnabled: boolean;
  notifyOnComplete: boolean;
  notifyOnError: boolean;
  defaultSearchSource: string;
  visibleSources: string[];
  searchProxyUrls: Record<string, string>;
  resultsPerPage: number;
  pageSize: number;
  anilistMaxPages: number;
  searchHistoryMaxItems: number;
  autocompleteMode: AutocompleteMode;
  anilistSuggestionBoost: "off" | "subtle" | "strong";
  videoExtensions: string[];
  audioExtensions: string[];
  subtitleExtensions: string[];
  showTrackFiles: "hide" | "torrent" | "folders";
  modalAnimation: boolean;
  enable3dBorders: boolean;
  buttonPressEffect: boolean;
  enableAnimations: boolean;
  modalBackdropOpacity: number;
  customScrollbar: boolean;
  retroStyle: "classic" | "soft" | "high-contrast";
  uiDensity: "comfortable" | "compact";
  savedFolderPaths: string[];
  hiddenPlayerFolders: string[];
  hiddenPlayerTorrents: string[];
  hidePlayerFolder: (path: string) => void;
  unhidePlayerFolder: (path: string) => void;
  hidePlayerTorrent: (infoHash: string) => void;
  unhidePlayerTorrent: (infoHash: string) => void;
  httpApiPort: number;
  ipv4Only: boolean;
  peerConnectTimeout: number;
  peerReadWriteTimeout: number;
  listenPort: number;
  enableUpnp: boolean;
  fastresumeEnabled: boolean;
  disablePersistence: boolean;
  parseTitles: boolean;
  anilistReleaseNotifications: boolean;
  notifyNewEpisodes: boolean;
  notifyStatusChanges: boolean;
  anilistPollIntervalMin: number;
  anilistNotifyLists: string[] | null;
  sqliteBrowserEnabled: boolean;
  sqliteShowImages: boolean;
  collectionTabEnabled: boolean;
  anilistTabEnabled: boolean;
  searchTabEnabled: boolean;
  torrentTabEnabled: boolean;
  playerTabEnabled: boolean;
  tmdbApiKey: string | null;
  tmdbProxyUrl: string | null;
  ffmpegSource: "essentials" | "github" | "github-mirror";
  fastembedSource: "q" | "full";
  searchSymSpellEnabled: boolean;
  searchSemanticEnabled: boolean;
  searchIntentEnabled: boolean;
  appFont: string | null;
  patch: (partial: Partial<SettingsStore>) => void;
}
