import { SearchFilters } from "@/types/anilist";

export const ANILIST_GENRES = [
  "Action",
  "Adventure",
  "Comedy",
  "Drama",
  "Ecchi",
  "Fantasy",
  "Hentai",
  "Horror",
  "Mahou Shoujo",
  "Mecha",
  "Music",
  "Mystery",
  "Psychological",
  "Romance",
  "Sci-Fi",
  "Slice of Life",
  "Sports",
  "Supernatural",
  "Thriller",
];

export const ANILIST_TAGS = [
  "Female Protagonist",
  "Male Protagonist",
  "Primarily Adult Cast",
  "Primarily Female Cast",
  "Primarily Male Cast",
  "Primarily Teen Cast",
  "Aliens",
  "Amnesia",
  "Angels",
  "Artificial Intelligence",
  "Butler",
  "Crossdressing",
  "Cyborg",
  "Delinquents",
  "Demons",
  "Detective",
  "Dragons",
  "Elf",
  "Ghost",
  "Goblin",
  "Gods",
  "Idol",
  "Kemonomimi",
  "Kuudere",
  "Maids",
  "Mermaid",
  "Monster Girl",
  "Nekomimi",
  "Ninja",
  "Nudity",
  "Ojou-sama",
  "Pirates",
  "Robots",
  "Samurai",
  "Succubus",
  "Teacher",
  "Tomboy",
  "Transgender",
  "Tsundere",
  "Twins",
  "Vampire",
  "VTuber",
  "Werewolf",
  "Witch",
  "Yandere",
  "Zombie",
  "Josei",
  "Kids",
  "Seinen",
  "Shoujo",
  "Shounen",
  "College",
  "Dungeon",
  "Prison",
  "Rural",
  "School",
  "Urban",
  "Dystopian",
  "Historical",
  "Medieval",
  "Time Skip",
  "Post-Apocalyptic",
  "Afterlife",
  "Alternate Universe",
  "Space",
  "Virtual World",
  "CGI",
  "Full CGI",
  "Full Color",
  "No Dialogue",
  "POV",
  "Archery",
  "Battle Royale",
  "Guns",
  "Martial Arts",
  "Swordplay",
  "Acting",
  "Band",
  "Dancing",
  "Drawing",
  "Fashion",
  "Food",
  "Classical Music",
  "Rock Music",
  "Parody",
  "Satire",
  "Slapstick",
  "Bullying",
  "Coming of Age",
  "Conspiracy",
  "Revenge",
  "Tragedy",
  "Alchemy",
  "Body Swapping",
  "Curses",
  "Exorcism",
  "Fairy Tale",
  "Isekai",
  "Reverse Isekai",
  "Kaiju",
  "Magic",
  "Mythology",
  "Necromancy",
  "Shapeshifting",
  "Steampunk",
  "Super Power",
  "Superhero",
  "Wuxia",
  "E-Sports",
  "Video Games",
  "Card Battle",
  "Mahjong",
  "Poker",
  "Baseball",
  "Basketball",
  "Boxing",
  "Cycling",
  "Football",
  "Swimming",
  "Tennis",
  "Volleyball",
  "Animals",
  "Body Horror",
  "Crime",
  "Crossover",
  "Death Game",
  "Drugs",
  "Gambling",
  "Gender Bending",
  "Gore",
  "LGBTQ+ Themes",
  "Marriage",
  "Politics",
  "Pregnancy",
  "Reincarnation",
  "Religion",
  "Survival",
  "War",
  "Assassins",
  "Cult",
  "Mafia",
  "Military",
  "Police",
  "Yakuza",
  "Aviation",
  "Cars",
  "Ships",
  "Trains",
  "Age Gap",
  "Boys' Love",
  "Cohabitation",
  "Female Harem",
  "Heterosexual",
  "Interspecies",
  "Love Triangle",
  "Male Harem",
  "Polyamorous",
  "Unrequited Love",
  "Yuri",
  "Cyberpunk",
  "Space Opera",
  "Time Loop",
  "Time Manipulation",
  "Tokusatsu",
  "Agriculture",
  "Cute Girls Doing Cute Things",
  "Family Life",
  "Iyashikei",
];

export const ANILIST_NSFW_TAGS = [
  "Ahegao",
  "Anal Sex",
  "Bondage",
  "Cheating",
  "Deepthroat",
  "Double Penetration",
  "Exhibitionism",
  "Facial",
  "Feet",
  "Fellatio",
  "Femdom",
  "Futanari",
  "Group Sex",
  "Handjob",
  "Incest",
  "Lactation",
  "Large Breasts",
  "Masturbation",
  "MILF",
  "Nakadashi",
  "Netorare",
  "Rape",
  "Sadism",
  "Sex Toys",
  "Sweat",
  "Tentacles",
  "Threesome",
  "Virginity",
  "Voyeur",
];
export const FORMATS = ["TV", "Movie", "OVA", "ONA", "Special", "Music"];
export const STATUSES = [
  "FINISHED",
  "RELEASING",
  "NOT_YET_RELEASED",
  "CANCELLED",
  "HIATUS",
];
export const SEASONS = ["WINTER", "SPRING", "SUMMER", "FALL"];

export const defaultFilters: SearchFilters = {
  tags: [],
  genres: [],
  format: "",
  status: "",
  season: "",
  seasonYear: null,
  adult: false,
  sort: "",
  source: "",
  country: "",
  year: [0, 0],
  episodes: [0, 0],
  score: [0, 0],
};
