//! Watch Party host runtime (P2): accept loop, handshake, roster, chat, and
//! liveness tracking over iroh.
//!
//! The host owns the room: it validates the join token, assigns viewer roles,
//! tracks peer liveness (6 s stale / 30 s drop), and fans out `ServerMessage`s
//! to every connected peer over reliable bi-streams.

use std::collections::{HashMap, HashSet, VecDeque};
use std::sync::atomic::{AtomicBool, AtomicU64, Ordering};
use std::sync::{Arc, Mutex};
use std::time::Duration;

use iroh::endpoint::{Connection, Incoming};
use iroh::Endpoint;
use serde::Serialize;
use tokio::sync::{broadcast, mpsc, oneshot, Notify};
use tokio::task::JoinHandle;

#[cfg(test)]
use crate::session::playlist::ReadySummary;
use crate::session::playlist::{peer_is_ready, PeerReport};
use crate::session::protocol::{
    chat_id_or_generate, sanitize_chat_text, sanitize_chat_upload, ChatAttachment, ChatMessage,
    ChatUpload, ClientMessage, ConnectionState, ControlAction, ErrorCode, ItemReport,
    MediaPlanItem, PeerInfo, PlaybackState, ProtocolError, Role, ServerMessage, WaitingFor,
    CHAT_ID_MAX_CHARS, CHAT_RATE_MAX, CHAT_RATE_WINDOW_SEC, PROTOCOL_VERSION,
    TYPING_MIN_INTERVAL_SEC,
};
use crate::session::state::{random_hex, SessionTicket, TrackState};
use crate::session::transport::{
    self, now_ms, FrameSender, LIVENESS_GRACE_MS, LIVENESS_TIMEOUT_MS,
};
use base64::{engine::general_purpose::STANDARD, Engine as _};

/// Room capacity for v1 watch parties.
pub const DEFAULT_MAX_PEERS: usize = 8;
/// Liveness polling period.
const LIVENESS_TICK_MS: u64 = 500;

/// Host configuration; ids are generated by [`HostConfig::generate`].
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct HostConfig {
    pub session_id: String,
    pub token: String,
    pub host_peer_id: String,
    pub display_name: String,
    pub max_peers: usize,
}

impl HostConfig {
    /// Build a fresh room identity for `display_name`.
    pub fn generate(display_name: String) -> Self {
        Self {
            session_id: random_hex(8),
            token: random_hex(16),
            host_peer_id: random_hex(8),
            display_name,
            max_peers: DEFAULT_MAX_PEERS,
        }
    }
}

/// Host-side events for the UI (roster, chat, control, and tracks).
#[derive(Debug, Clone, PartialEq, Serialize)]
#[serde(tag = "kind", rename_all = "camelCase")]
pub enum HostEvent {
    Roster {
        peers: Vec<PeerInfo>,
    },
    Chat {
        message: ChatMessage,
        /// Attached `.torrent` bytes (base64); the pump keeps them in the
        /// bounded side map while the message itself carries metadata only.
        attachment: Option<ChatUpload>,
    },
    PeerJoined {
        peer_id: String,
        display_name: String,
    },
    PeerLeft {
        peer_id: String,
    },
    /// A guest asked for control; the host applies it locally too.
    Control {
        revision: u64,
        action: ControlAction,
    },
    /// The room's track selection changed.
    Track {
        track: TrackState,
    },
    /// The host started a plan item; the frontend opens `path` in the player.
    StartItem {
        item_id: String,
        path: Option<String>,
    },
    /// The room is holding a start (an empty `peer_ids` clears the wait).
    Waiting {
        item_id: String,
        peer_ids: Vec<String>,
    },
    /// A guest (or the host itself) started or stopped typing.
    Typing {
        peer_id: String,
        active: bool,
    },
}

struct PeerEntry {
    peer_id: String,
    display_name: String,
    anilist_user_id: Option<u64>,
    role: Role,
    ready: bool,
    stale: bool,
    /// Set once the peer is silent past the 30 s grace window; cleared on its
    /// next `Hello`. A left peer remains in the roster but is excluded from the
    /// ready gate and the missing-file computation.
    left: bool,
    /// The peer's dialable endpoint, read from the QUIC handshake. Carried in
    /// the roster so an elected successor can be reached after this host dies.
    endpoint_id: String,
    last_seen_ms: Arc<AtomicU64>,
    outbound: mpsc::UnboundedSender<ServerMessage>,
}

struct HostInner {
    endpoint: Endpoint,
    config: HostConfig,
    peers: Mutex<HashMap<String, PeerEntry>>,
    events: broadcast::Sender<HostEvent>,
    revision: AtomicU64,
    playback: Mutex<Option<PlaybackState>>,
    track: Mutex<Option<TrackState>>,
    plan: Mutex<Vec<MediaPlanItem>>,
    reports: Mutex<HashMap<String, PeerReport>>,
    /// Host-local item id → file path; never sent to guests.
    paths: Mutex<HashMap<String, String>>,
    /// The item the room is currently holding a start on, plus who is missing it.
    waiting: Mutex<Option<WaitingFor>>,
    /// A pending handover: which peer was asked to take over, and the channel
    /// that resolves when it answers `HandoverReady`.
    handover: Mutex<Option<HandoverWaiter>>,
    /// Roster carried over from the outgoing host after a handover. Roles and
    /// readiness are re-applied as each peer reconnects (their peer ids are
    /// stable), so the roster survives the migration.
    carried: Mutex<Vec<PeerInfo>>,
    /// Sliding window of recent chat timestamps (seconds) per peer id, for
    /// the outbound chat rate limit.
    chat_stamps: Mutex<HashMap<String, VecDeque<f64>>>,
    /// Last accepted typing frame per peer (seconds); keeps a flood of
    /// `Typing` frames from spamming every room UI.
    typing_stamps: Mutex<HashMap<String, f64>>,
    shutdown: AtomicBool,
    shutdown_notify: Notify,
}

/// The in-flight host handover awaiting its successor's confirmation.
struct HandoverWaiter {
    peer_id: String,
    tx: oneshot::Sender<Result<Handover, String>>,
}

/// A successor that accepted the room: who it is and where it now listens.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Handover {
    /// The successor's roster peer id (the new host).
    pub host_id: String,
    /// The successor's endpoint id; the ticket guests must dial.
    pub endpoint_id: String,
}

/// Result of a start request.
#[derive(Debug, Clone, PartialEq, Eq, Serialize)]
#[serde(tag = "status", rename_all = "camelCase")]
pub enum StartOutcome {
    /// Playback started; `path` is the host-local file for the item, if known.
    Started {
        item_id: String,
        path: Option<String>,
    },
    /// The start is held until every `peer_ids` peer has the item.
    Waiting {
        item_id: String,
        peer_ids: Vec<String>,
    },
}

impl HostInner {
    fn peer_info(entry: &PeerEntry) -> PeerInfo {
        PeerInfo {
            peer_id: entry.peer_id.clone(),
            display_name: entry.display_name.clone(),
            avatar_seed: entry.peer_id.clone(),
            anilist_user_id: entry.anilist_user_id,
            role: entry.role,
            connection: if entry.left {
                ConnectionState::Disconnected
            } else if entry.stale {
                ConnectionState::Stale
            } else {
                ConnectionState::Direct
            },
            ready: entry.ready,
            drift_ms: 0.0,
            rtt_ms: 0.0,
            buffering: false,
            left: entry.left,
            endpoint_id: entry.endpoint_id.clone(),
        }
    }

    fn host_info(&self) -> PeerInfo {
        PeerInfo {
            peer_id: self.config.host_peer_id.clone(),
            display_name: self.config.display_name.clone(),
            avatar_seed: self.config.host_peer_id.clone(),
            anilist_user_id: None,
            role: Role::Host,
            connection: ConnectionState::Direct,
            ready: true,
            drift_ms: 0.0,
            rtt_ms: 0.0,
            buffering: false,
            left: false,
            endpoint_id: self.endpoint.id().to_string(),
        }
    }

    fn roster(&self) -> Vec<PeerInfo> {
        let peers = self.peers.lock().expect("session peers poisoned");
        let mut out = Vec::with_capacity(peers.len() + 1);
        out.push(self.host_info());
        out.extend(peers.values().map(Self::peer_info));
        out
    }

    fn broadcast(&self, message: ServerMessage) {
        let peers = self.peers.lock().expect("session peers poisoned");
        for entry in peers.values() {
            let _ = entry.outbound.send(message.clone());
        }
    }

    fn send_to(&self, peer_id: &str, message: ServerMessage) {
        let peers = self.peers.lock().expect("session peers poisoned");
        if let Some(entry) = peers.get(peer_id) {
            let _ = entry.outbound.send(message);
        }
    }

    fn broadcast_roster(&self) {
        let peers = self.roster();
        self.broadcast(ServerMessage::Roster {
            peers: peers.clone(),
        });
        let _ = self.events.send(HostEvent::Roster { peers });
    }

    fn add_chat(
        &self,
        id: String,
        from: String,
        text: String,
        reply_to: Option<String>,
        upload: Option<(String, Vec<u8>)>,
    ) -> ChatMessage {
        let (meta, wire) = match upload {
            Some((name, bytes)) => (
                Some(ChatAttachment {
                    name: name.clone(),
                    size: bytes.len(),
                }),
                Some(ChatUpload {
                    name,
                    data: STANDARD.encode(&bytes),
                }),
            ),
            None => (None, None),
        };
        let message = ChatMessage {
            id,
            from,
            text,
            at: now_ms() as f64 / 1000.0,
            links: Vec::new(),
            reply_to,
            attachment: meta,
        };
        self.broadcast(ServerMessage::Chat {
            id: message.id.clone(),
            from: message.from.clone(),
            text: message.text.clone(),
            at: message.at,
            links: message.links.clone(),
            reply_to: message.reply_to.clone(),
            attachment: wire.clone(),
        });
        let _ = self.events.send(HostEvent::Chat {
            message: message.clone(),
            attachment: wire,
        });
        message
    }

    /// Sliding-window chat rate check for one peer: records `now` and reports
    /// whether the peer is still inside [`CHAT_RATE_MAX`] lines per window.
    fn allow_chat(&self, peer_id: &str, now: f64) -> bool {
        let mut stamps = self
            .chat_stamps
            .lock()
            .expect("session chat stamps poisoned");
        let queue = stamps.entry(peer_id.to_string()).or_default();
        while queue
            .front()
            .is_some_and(|oldest| now - *oldest > CHAT_RATE_WINDOW_SEC)
        {
            queue.pop_front();
        }
        if queue.len() >= CHAT_RATE_MAX {
            return false;
        }
        queue.push_back(now);
        true
    }

    /// Broadcast `message` to every peer except `except` (so a sender never
    /// hears its own frame echoed back).
    fn broadcast_except(&self, except: &str, message: ServerMessage) {
        let peers = self.peers.lock().expect("session peers poisoned");
        for (peer_id, entry) in peers.iter() {
            if peer_id != except {
                let _ = entry.outbound.send(message.clone());
            }
        }
    }

    /// Typing throttle for one peer: stop frames always pass so an indicator
    /// can clear, start frames need [`TYPING_MIN_INTERVAL_SEC`] of spacing.
    fn allow_typing(&self, peer_id: &str, active: bool, now: f64) -> bool {
        if !active {
            return true;
        }
        let mut stamps = self
            .typing_stamps
            .lock()
            .expect("session typing stamps poisoned");
        if stamps
            .get(peer_id)
            .is_some_and(|last| now - *last < TYPING_MIN_INTERVAL_SEC)
        {
            return false;
        }
        stamps.insert(peer_id.to_string(), now);
        true
    }

    fn remove_peer(&self, peer_id: &str) {
        let removed = self
            .peers
            .lock()
            .expect("session peers poisoned")
            .remove(peer_id);
        if let Some(entry) = removed {
            let _ = self.events.send(HostEvent::PeerLeft {
                peer_id: entry.peer_id,
            });
            self.broadcast_roster();
            self.recheck_waiting();
        }
    }

    /// Advance liveness at `now`: mark newly stale peers and mark peers left
    /// past the grace window. Left peers stay in the roster (so every UI can
    /// show the badge) but stop gating the room, so the held start is
    /// re-evaluated with [`Self::recheck_waiting`]. Returns the peers that
    /// crossed into `left` on this tick (never auto-resumes anything).
    fn apply_liveness(&self, now: u64) -> Vec<String> {
        let mut newly_left = Vec::new();
        let changed = {
            let mut peers = self.peers.lock().expect("session peers poisoned");
            let mut changed = false;
            for entry in peers.values_mut() {
                match peer_liveness(now, entry.last_seen_ms.load(Ordering::Relaxed), entry.stale) {
                    PeerLiveness::Drop => {
                        if !entry.left {
                            entry.left = true;
                            entry.stale = true;
                            newly_left.push(entry.peer_id.clone());
                            changed = true;
                        }
                    }
                    PeerLiveness::Stale => {
                        if !entry.stale {
                            entry.stale = true;
                            changed = true;
                        }
                    }
                    PeerLiveness::Alive => {}
                }
            }
            changed
        };
        if changed {
            self.broadcast_roster();
        }
        if !newly_left.is_empty() {
            // A held start may now be over; clearing it never starts anything...
            self.recheck_waiting();
            // ...and an active playback pauses for everyone (no auto-resume).
            self.pause_for_departures();
        }
        newly_left
    }

    /// Pause an active playback because a peer went past the grace window.
    /// Never resumes: a resume must arrive as an explicit host/moderator
    /// command (lobby.md §14.3).
    fn pause_for_departures(&self) {
        let state = self
            .playback
            .lock()
            .expect("session playback poisoned")
            .clone();
        let Some(state) = state else {
            return;
        };
        if !state.is_playing || state.media_id.is_empty() {
            return;
        }
        let elapsed = (now_ms() as f64 - state.updated_at_mono).max(0.0) / 1000.0;
        let position = (state.position + elapsed * state.rate).max(0.0);
        self.publish_position(state.media_id, position, false, state.rate);
    }

    fn next_revision(&self) -> u64 {
        self.revision.fetch_add(1, Ordering::SeqCst) + 1
    }

    /// Broadcast a control event and return its revision.
    fn relay_control(&self, action: ControlAction) -> u64 {
        let revision = self.next_revision();
        self.broadcast(ServerMessage::Command {
            revision,
            action: action.clone(),
        });
        let _ = self.events.send(HostEvent::Control { revision, action });
        revision
    }

    /// Store and broadcast the authoritative playback snapshot.
    fn publish_playback(&self, state: &PlaybackState) {
        *self.playback.lock().expect("session playback poisoned") = Some(state.clone());
        self.broadcast(ServerMessage::PlaybackState {
            revision: state.revision,
            media_id: state.media_id.clone(),
            position: state.position,
            is_playing: state.is_playing,
            rate: state.rate,
            updated_at_mono: state.updated_at_mono,
        });
    }

    /// Stamp a fresh snapshot (next revision, host clock) and broadcast it.
    ///
    /// The host clock timestamp is authoritative: guests align their clock
    /// estimate against it, so the frontend must not supply its own.
    fn publish_position(
        &self,
        media_id: String,
        position: f64,
        is_playing: bool,
        rate: f64,
    ) -> PlaybackState {
        let state = PlaybackState {
            revision: self.next_revision(),
            media_id,
            position,
            is_playing,
            rate,
            updated_at_mono: now_ms() as f64,
        };
        self.publish_playback(&state);
        state
    }

    /// Store and broadcast the room's track selection.
    fn set_track(&self, track: TrackState) {
        self.broadcast(ServerMessage::TrackSync {
            media_id: track.media_id.clone(),
            audio: track.audio.clone(),
            sub: track.sub.clone(),
            audio_delay: track.audio_delay,
            sub_delay: track.sub_delay,
        });
        let _ = self.events.send(HostEvent::Track {
            track: track.clone(),
        });
        *self.track.lock().expect("session track poisoned") = Some(track);
    }

    /// The current room track selection.
    fn last_track(&self) -> Option<TrackState> {
        self.track.lock().expect("session track poisoned").clone()
    }

    /// The current media plan.
    fn plan(&self) -> Vec<MediaPlanItem> {
        self.plan.lock().expect("session plan poisoned").clone()
    }

    /// Replace the media plan, broadcast it, and re-evaluate the ready gate.
    ///
    /// `paths` is the host-local item id → file path map; it is pruned to the
    /// ids present in `items` and never sent to guests.
    fn set_plan(&self, items: Vec<MediaPlanItem>, paths: HashMap<String, String>) {
        let ids: HashSet<&str> = items.iter().map(|item| item.item_id.as_str()).collect();
        let paths = paths
            .into_iter()
            .filter(|(id, _)| ids.contains(id.as_str()))
            .collect();
        *self.plan.lock().expect("session plan poisoned") = items.clone();
        *self.paths.lock().expect("session paths poisoned") = paths;
        self.broadcast(ServerMessage::MediaPlan { items });
        self.recompute_readiness();
    }

    /// The host-local path recorded for an item, if any.
    fn item_path(&self, item_id: &str) -> Option<String> {
        self.paths
            .lock()
            .expect("session paths poisoned")
            .get(item_id)
            .cloned()
    }

    /// For each plan item, the guest peer ids yet to report it present.
    /// Peers marked left are ignored: they no longer gate the room.
    fn missing_map(&self) -> HashMap<String, Vec<String>> {
        let peer_ids: Vec<String> = self
            .peers
            .lock()
            .expect("session peers poisoned")
            .values()
            .filter(|entry| !entry.left)
            .map(|entry| entry.peer_id.clone())
            .collect();
        let item_reports: HashMap<String, Vec<ItemReport>> = self
            .reports
            .lock()
            .expect("session reports poisoned")
            .iter()
            .map(|(peer_id, report)| (peer_id.clone(), report.items.clone()))
            .collect();
        crate::session::playlist::missing_by_item(&self.plan(), &peer_ids, &item_reports)
    }

    /// Guest peer ids that have not reported `item_id` as present.
    fn missing_peers(&self, item_id: &str) -> Vec<String> {
        let reports = self.reports.lock().expect("session reports poisoned");
        let peers = self.peers.lock().expect("session peers poisoned");
        let mut missing: Vec<String> = peers
            .values()
            .filter(|entry| !entry.left)
            .filter(|entry| {
                !reports
                    .get(&entry.peer_id)
                    .and_then(|report| report.items.iter().find(|entry| entry.item_id == item_id))
                    .is_some_and(|entry| entry.present)
            })
            .map(|entry| entry.peer_id.clone())
            .collect();
        missing.sort();
        missing
    }

    /// The role of a roster peer (the host is always [`Role::Host`]).
    fn role_of(&self, peer_id: &str) -> Option<Role> {
        if peer_id == self.config.host_peer_id {
            return Some(Role::Host);
        }
        self.peers
            .lock()
            .expect("session peers poisoned")
            .get(peer_id)
            .map(|entry| entry.role)
    }

    /// Whether a peer may start items (host or moderator).
    fn can_start(&self, peer_id: &str) -> bool {
        matches!(self.role_of(peer_id), Some(Role::Host | Role::Moderator))
    }

    /// Whether a peer may attach a `.torrent` to chat (host or moderator).
    /// Same set as [`HostInner::can_start`], kept separate so the rights can
    /// diverge later.
    fn can_attach(&self, peer_id: &str) -> bool {
        matches!(self.role_of(peer_id), Some(Role::Host | Role::Moderator))
    }

    /// Accept a peer's chat upload: host/moderator only, valid base64, and a
    /// `.torrent` name with bytes that fit the frame. Returns the cleaned
    /// name with the raw bytes; viewers' uploads are stripped (`None`) while
    /// their text still goes through.
    fn accept_upload(
        &self,
        peer_id: &str,
        attachment: Option<ChatUpload>,
    ) -> Option<(String, Vec<u8>)> {
        let upload = attachment?;
        if !self.can_attach(peer_id) {
            return None;
        }
        let bytes = STANDARD.decode(&upload.data).ok()?;
        let name = sanitize_chat_upload(&upload.name, bytes.len())?;
        Some((name, bytes))
    }

    /// The role/ready a peer carried over from the outgoing host, if any.
    fn carried_entry(&self, peer_id: &str) -> Option<PeerInfo> {
        self.carried
            .lock()
            .expect("session carried roster poisoned")
            .iter()
            .find(|peer| peer.peer_id == peer_id)
            .cloned()
    }

    /// Seed the carried roster after a handover (roles/ready survive).
    fn set_carried(&self, roster: Vec<PeerInfo>) {
        *self
            .carried
            .lock()
            .expect("session carried roster poisoned") = roster;
    }

    /// Host: ask `peer_id` to take over the room; resolves when it answers
    /// [`ClientMessage::HandoverReady`] with its new endpoint id.
    fn begin_handover(
        &self,
        peer_id: &str,
    ) -> Result<oneshot::Receiver<Result<Handover, String>>, String> {
        if peer_id == self.config.host_peer_id {
            return Err("the host cannot hand the room over to itself".to_string());
        }
        let (tx, rx) = oneshot::channel();
        {
            let peers = self.peers.lock().expect("session peers poisoned");
            if !peers.contains_key(peer_id) {
                return Err(format!("no peer {peer_id}"));
            }
        }
        let mut pending = self.handover.lock().expect("session handover poisoned");
        if pending.is_some() {
            return Err("a handover is already in progress".to_string());
        }
        *pending = Some(HandoverWaiter {
            peer_id: peer_id.to_string(),
            tx,
        });
        drop(pending);
        let playback = self
            .playback
            .lock()
            .expect("session playback poisoned")
            .clone();
        self.send_to(
            peer_id,
            ServerMessage::HostHandover {
                session_id: self.config.session_id.clone(),
                token: self.config.token.clone(),
                playback,
            },
        );
        Ok(rx)
    }

    /// Resolve a pending handover when the successor confirms its endpoint.
    fn resolve_handover(&self, peer_id: &str, endpoint_id: String) -> bool {
        let mut pending = self.handover.lock().expect("session handover poisoned");
        // Not our pending successor (or none): leave the waiter untouched.
        if !matches!(&*pending, Some(waiter) if waiter.peer_id == peer_id) {
            return false;
        }
        let Some(waiter) = pending.take() else {
            return false;
        };
        drop(pending);
        let _ = waiter.tx.send(Ok(Handover {
            host_id: peer_id.to_string(),
            endpoint_id,
        }));
        true
    }

    /// Tell every guest where the room moved; sent right before the old host
    /// stops so they can dial the successor's endpoint.
    fn announce_migration(&self, handover: &Handover) {
        self.broadcast(ServerMessage::Migrate {
            session_id: self.config.session_id.clone(),
            token: self.config.token.clone(),
            endpoint_id: handover.endpoint_id.clone(),
            host_id: handover.host_id.clone(),
        });
    }

    /// Host: promote or demote a guest. The host role itself is immutable.
    fn set_role(&self, peer_id: &str, role: Role) -> Result<(), String> {
        if peer_id == self.config.host_peer_id {
            return Err("the host role cannot be changed".to_string());
        }
        if role == Role::Host {
            return Err("a guest cannot be promoted to host".to_string());
        }
        let changed = {
            let mut peers = self.peers.lock().expect("session peers poisoned");
            match peers.get_mut(peer_id) {
                Some(entry) if entry.role != role => {
                    entry.role = role;
                    true
                }
                Some(_) => false,
                None => return Err(format!("no peer {peer_id}")),
            }
        };
        if changed {
            self.broadcast_roster();
        }
        Ok(())
    }

    /// Host/moderator: start a plan item, or hold the start while peers are missing it.
    fn start_item(&self, item_id: &str) -> Result<StartOutcome, String> {
        let item = self
            .plan()
            .into_iter()
            .find(|item| item.item_id == item_id)
            .ok_or_else(|| format!("no plan item {item_id}"))?;
        let missing = self.missing_peers(item_id);
        if missing.is_empty() {
            *self.waiting.lock().expect("session waiting poisoned") = None;
            self.broadcast(ServerMessage::WaitingFor {
                item_id: item.item_id.clone(),
                peer_ids: Vec::new(),
            });
            let _ = self.events.send(HostEvent::Waiting {
                item_id: item.item_id.clone(),
                peer_ids: Vec::new(),
            });
            self.publish_position(item.item_id.clone(), 0.0, true, 1.0);
            self.broadcast(ServerMessage::Command {
                revision: self.next_revision(),
                action: ControlAction::Load {
                    media_id: item.item_id.clone(),
                },
            });
            let path = self.item_path(item_id);
            let _ = self.events.send(HostEvent::StartItem {
                item_id: item.item_id.clone(),
                path: path.clone(),
            });
            Ok(StartOutcome::Started {
                item_id: item.item_id,
                path,
            })
        } else {
            *self.waiting.lock().expect("session waiting poisoned") = Some(WaitingFor {
                item_id: item.item_id.clone(),
                peer_ids: missing.clone(),
            });
            self.broadcast(ServerMessage::WaitingFor {
                item_id: item.item_id.clone(),
                peer_ids: missing.clone(),
            });
            let _ = self.events.send(HostEvent::Waiting {
                item_id: item.item_id.clone(),
                peer_ids: missing.clone(),
            });
            self.publish_position(item.item_id.clone(), 0.0, false, 1.0);
            Ok(StartOutcome::Waiting {
                item_id: item.item_id,
                peer_ids: missing,
            })
        }
    }

    /// The current waiting state, if a start is held.
    fn waiting_state(&self) -> Option<WaitingFor> {
        self.waiting
            .lock()
            .expect("session waiting poisoned")
            .clone()
    }

    /// Re-evaluate a held start against the latest reports; clears or narrows it.
    ///
    /// Never auto-starts: when the missing set empties the wait is only cleared,
    /// so the host/moderator still presses start themselves.
    fn recheck_waiting(&self) {
        let Some(waiting) = self.waiting_state() else {
            return;
        };
        let missing = self.missing_peers(&waiting.item_id);
        if missing == waiting.peer_ids {
            return;
        }
        if missing.is_empty() {
            *self.waiting.lock().expect("session waiting poisoned") = None;
        } else {
            *self.waiting.lock().expect("session waiting poisoned") = Some(WaitingFor {
                item_id: waiting.item_id.clone(),
                peer_ids: missing.clone(),
            });
        }
        self.broadcast(ServerMessage::WaitingFor {
            item_id: waiting.item_id.clone(),
            peer_ids: missing.clone(),
        });
        let _ = self.events.send(HostEvent::Waiting {
            item_id: waiting.item_id,
            peer_ids: missing,
        });
    }

    /// Store a guest readiness report, broadcast its verdict, and update the
    /// roster entry using the current plan.
    fn record_state_report(&self, peer_id: &str, ready: bool, items: Vec<ItemReport>) {
        let verdict = {
            let plan = self.plan();
            let report = PeerReport {
                peer_id: peer_id.to_string(),
                items: items.clone(),
                ready,
            };
            let verdict = peer_is_ready(&report, &plan);
            self.reports
                .lock()
                .expect("session reports poisoned")
                .insert(peer_id.to_string(), report);
            verdict
        };
        self.broadcast(ServerMessage::ReadyState {
            peer_id: peer_id.to_string(),
            ready: verdict,
            items,
        });
        let changed = {
            let mut peers = self.peers.lock().expect("session peers poisoned");
            match peers.get_mut(peer_id) {
                Some(entry) if entry.ready != verdict => {
                    entry.ready = verdict;
                    true
                }
                _ => false,
            }
        };
        if changed {
            self.broadcast_roster();
        }
        self.recheck_waiting();
    }

    /// Re-evaluate every stored report against the current plan.
    fn recompute_readiness(&self) {
        let plan = self.plan();
        let reports = self
            .reports
            .lock()
            .expect("session reports poisoned")
            .clone();
        let mut changed = false;
        {
            let mut peers = self.peers.lock().expect("session peers poisoned");
            for (peer_id, report) in &reports {
                let verdict = peer_is_ready(report, &plan);
                if let Some(entry) = peers.get_mut(peer_id) {
                    if entry.ready != verdict {
                        entry.ready = verdict;
                        changed = true;
                    }
                }
            }
        }
        if changed {
            self.broadcast_roster();
        }
    }

    /// Ready gate aggregated from the roster against the current plan.
    #[cfg(test)]
    fn ready_summary(&self) -> ReadySummary {
        crate::session::playlist::roster_ready_summary(&self.plan(), &self.roster())
    }

    /// Insert a synthetic peer without a live connection (unit tests only).
    #[cfg(test)]
    fn insert_test_peer(&self, peer_id: &str, role: Role) {
        let (out_tx, _out_rx) = mpsc::unbounded_channel();
        self.peers.lock().expect("session peers poisoned").insert(
            peer_id.to_string(),
            PeerEntry {
                peer_id: peer_id.to_string(),
                display_name: peer_id.to_string(),
                anilist_user_id: None,
                role,
                ready: true,
                stale: false,
                left: false,
                endpoint_id: String::new(),
                last_seen_ms: Arc::new(AtomicU64::new(now_ms())),
                outbound: out_tx,
            },
        );
    }
}

/// A running host session.
#[derive(Clone)]
pub struct HostSession {
    inner: Arc<HostInner>,
    accept_task: Arc<JoinHandle<()>>,
    liveness_task: Arc<JoinHandle<()>>,
}

impl HostSession {
    /// Bind the public n0 endpoint and start hosting.
    pub async fn start(config: HostConfig) -> Result<Self, String> {
        let endpoint = transport::bind_endpoint().await?;
        Ok(Self::bind(config, endpoint))
    }

    /// Start hosting on an already-bound endpoint (used by tests/harness).
    pub fn bind(config: HostConfig, endpoint: Endpoint) -> Self {
        let (events, _) = broadcast::channel(128);
        let inner = Arc::new(HostInner {
            endpoint,
            config,
            peers: Mutex::new(HashMap::new()),
            events,
            revision: AtomicU64::new(0),
            playback: Mutex::new(None),
            track: Mutex::new(None),
            plan: Mutex::new(Vec::new()),
            reports: Mutex::new(HashMap::new()),
            paths: Mutex::new(HashMap::new()),
            waiting: Mutex::new(None),
            handover: Mutex::new(None),
            carried: Mutex::new(Vec::new()),
            chat_stamps: Mutex::new(HashMap::new()),
            typing_stamps: Mutex::new(HashMap::new()),
            shutdown: AtomicBool::new(false),
            shutdown_notify: Notify::new(),
        });
        let accept_task = Arc::new(tokio::spawn(run_accept(inner.clone())));
        let liveness_task = Arc::new(tokio::spawn(run_liveness(inner.clone())));
        Self {
            inner,
            accept_task,
            liveness_task,
        }
    }

    /// The join ticket a guest needs.
    pub fn ticket(&self) -> SessionTicket {
        SessionTicket {
            session_id: self.inner.config.session_id.clone(),
            token: self.inner.config.token.clone(),
            endpoint_id: self.inner.endpoint.id().to_string(),
        }
    }

    /// The underlying endpoint (tests dial it directly).
    pub fn endpoint(&self) -> &Endpoint {
        &self.inner.endpoint
    }

    /// The room id.
    pub fn session_id(&self) -> &str {
        &self.inner.config.session_id
    }

    /// The host's roster peer id.
    pub fn host_peer_id(&self) -> &str {
        &self.inner.config.host_peer_id
    }

    /// The host's display name.
    pub fn display_name(&self) -> &str {
        &self.inner.config.display_name
    }

    /// Tell every guest that the host started or stopped typing. The host's
    /// own UI never shows its own typing line, so no local event is emitted.
    pub fn broadcast_typing(&self, active: bool) {
        self.inner.broadcast(ServerMessage::Typing {
            peer_id: self.inner.config.host_peer_id.clone(),
            active,
        });
    }

    /// Number of connected guests.
    #[cfg(test)]
    pub fn peer_count(&self) -> usize {
        self.inner
            .peers
            .lock()
            .expect("session peers poisoned")
            .len()
    }

    /// Subscribe to host-side UI events.
    pub fn subscribe(&self) -> broadcast::Receiver<HostEvent> {
        self.inner.events.subscribe()
    }

    /// Current roster (host first, then guests).
    pub fn roster(&self) -> Vec<PeerInfo> {
        self.inner.roster()
    }

    /// Record and broadcast a chat line; returns the stored message.
    /// `upload` is a validated `.torrent` name with its raw bytes (the
    /// caller stores the bytes in the mirror; the wire form is derived here).
    pub fn add_chat(
        &self,
        id: String,
        from: String,
        text: String,
        reply_to: Option<String>,
        upload: Option<(String, Vec<u8>)>,
    ) -> ChatMessage {
        self.inner.add_chat(id, from, text, reply_to, upload)
    }

    /// Apply a control action locally and broadcast it; returns the revision.
    pub fn relay_control(&self, action: ControlAction) -> u64 {
        self.inner.relay_control(action)
    }

    /// Store and broadcast the authoritative playback snapshot.
    #[cfg(test)]
    pub fn publish_playback(&self, state: PlaybackState) {
        self.inner.publish_playback(&state);
    }

    /// Stamp a fresh snapshot (next revision, host clock) and broadcast it.
    pub fn publish_position(
        &self,
        media_id: String,
        position: f64,
        is_playing: bool,
        rate: f64,
    ) -> PlaybackState {
        self.inner
            .publish_position(media_id, position, is_playing, rate)
    }

    /// Store and broadcast the room's track selection.
    pub fn sync_tracks(&self, track: TrackState) {
        self.inner.set_track(track);
    }

    /// The most recently published playback snapshot.
    pub fn last_playback(&self) -> Option<PlaybackState> {
        self.inner
            .playback
            .lock()
            .expect("session playback poisoned")
            .clone()
    }

    /// The current room track selection.
    #[cfg(test)]
    pub fn last_track(&self) -> Option<TrackState> {
        self.inner.last_track()
    }

    /// The current media plan.
    #[cfg(test)]
    pub fn plan(&self) -> Vec<MediaPlanItem> {
        self.inner.plan()
    }

    /// Replace the media plan and broadcast it to every guest.
    ///
    /// `paths` is the host-local item id → file path map; it is stored on the
    /// host only and never sent to guests.
    pub fn set_plan(&self, items: Vec<MediaPlanItem>, paths: HashMap<String, String>) {
        self.inner.set_plan(items, paths);
    }

    /// Host: promote or demote a guest (the host role is immutable).
    pub fn set_role(&self, peer_id: &str, role: Role) -> Result<(), String> {
        self.inner.set_role(peer_id, role)
    }

    /// Host: ask `peer_id` to take over the room. The receiver resolves once
    /// the successor's [`ClientMessage::HandoverReady`] arrives, or with an
    /// error when the successor reports a failure.
    pub fn begin_handover(
        &self,
        peer_id: &str,
    ) -> Result<oneshot::Receiver<Result<Handover, String>>, String> {
        self.inner.begin_handover(peer_id)
    }

    /// Adopt the state carried over from a handover: the roster (roles/ready
    /// re-applied as peers reconnect with their stable peer ids), the held
    /// start, and the playback snapshot position/pause survive the move.
    pub fn adopt_state(
        &self,
        roster: Vec<PeerInfo>,
        waiting: Option<WaitingFor>,
        playback: Option<PlaybackState>,
    ) {
        self.inner.set_carried(roster);
        *self.inner.waiting.lock().expect("session waiting poisoned") = waiting;
        // Seed the revision counter from the carried snapshot: the successor's
        // own counter starts at 0, so without this its first snapshot would be
        // dropped by every guest as a stale revision (lobby.md §14.7).
        if let Some(state) = &playback {
            self.inner
                .revision
                .fetch_max(state.revision, Ordering::SeqCst);
        }
        *self
            .inner
            .playback
            .lock()
            .expect("session playback poisoned") = playback;
    }

    /// Announce the room's new location to every guest, wait for the frames to
    /// flush, then stop hosting. Runs at the end of a transfer so the old host
    /// can rejoin as a guest.
    pub async fn finish_handover(&self, handover: &Handover) {
        self.inner.announce_migration(handover);
        // Per-peer writer tasks drain their queues asynchronously; give them a
        // beat before closing the endpoint drops the connections.
        tokio::time::sleep(Duration::from_millis(300)).await;
        self.stop().await;
    }

    /// Host/moderator: start a plan item, or hold until peers have the file.
    pub fn start_item(&self, item_id: &str) -> Result<StartOutcome, String> {
        self.inner.start_item(item_id)
    }

    /// The item the room is currently holding a start on, if any.
    pub fn waiting(&self) -> Option<WaitingFor> {
        self.inner.waiting_state()
    }

    /// For each plan item, the guest peer ids yet to report it present.
    pub fn missing(&self) -> HashMap<String, Vec<String>> {
        self.inner.missing_map()
    }

    /// The ready gate aggregated from the roster and the current plan.
    #[cfg(test)]
    pub fn ready_summary(&self) -> ReadySummary {
        self.inner.ready_summary()
    }

    /// Stop hosting and close the endpoint.
    pub async fn stop(&self) {
        self.inner.shutdown.store(true, Ordering::SeqCst);
        self.inner.shutdown_notify.notify_waiters();
        self.inner
            .peers
            .lock()
            .expect("session peers poisoned")
            .clear();
        self.inner.endpoint.close().await;
        self.accept_task.abort();
        self.liveness_task.abort();
    }
}

async fn run_accept(inner: Arc<HostInner>) {
    loop {
        if inner.shutdown.load(Ordering::SeqCst) {
            break;
        }
        tokio::select! {
            incoming = inner.endpoint.accept() => {
                let Some(incoming) = incoming else { break };
                let inner = inner.clone();
                tokio::spawn(async move { handle_connection(inner, incoming).await });
            }
            () = inner.shutdown_notify.notified() => {}
        }
    }
}

async fn run_liveness(inner: Arc<HostInner>) {
    loop {
        tokio::time::sleep(Duration::from_millis(LIVENESS_TICK_MS)).await;
        if inner.shutdown.load(Ordering::SeqCst) {
            break;
        }
        inner.apply_liveness(now_ms());
    }
}

/// Liveness verdict for one peer at a point in time.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum PeerLiveness {
    /// Fresh enough; no change.
    Alive,
    /// Silent past the timeout; mark as stale.
    Stale,
    /// Silent past the grace period; mark as left (kept in the roster).
    Drop,
}

/// Classify a peer from `now`, its last-seen timestamp, and current staleness.
pub fn peer_liveness(now: u64, last_seen: u64, stale: bool) -> PeerLiveness {
    let age = now.saturating_sub(last_seen);
    if age > LIVENESS_GRACE_MS {
        PeerLiveness::Drop
    } else if age > LIVENESS_TIMEOUT_MS && !stale {
        PeerLiveness::Stale
    } else {
        PeerLiveness::Alive
    }
}

async fn reject(connection: &Connection, sender: &mut FrameSender, code: ErrorCode, message: &str) {
    let _ = sender
        .send(&ServerMessage::Error {
            code,
            message: message.to_string(),
        })
        .await;
    let _ = sender.send(&ServerMessage::Bye).await;
    sender.finish();
    // Keep the connection alive until the peer drains the rejection frames:
    // dropping or hard-closing it here would discard the stream.
    let _ = tokio::time::timeout(Duration::from_secs(2), connection.closed()).await;
    connection.close(1u32.into(), b"rejected");
}

async fn handle_connection(inner: Arc<HostInner>, incoming: Incoming) {
    let Ok(connection) = incoming.await else {
        return;
    };
    let (send, recv) = match connection.accept_bi().await {
        Ok(pair) => pair,
        Err(_) => {
            connection.close(0u32.into(), b"no stream");
            return;
        }
    };
    let (mut sender, mut reader) = transport::channel(send, recv);

    let frame = match reader.recv().await {
        Ok(frame) => frame,
        Err(_) => return,
    };
    let hello = match frame.client() {
        Ok(ClientMessage::Hello {
            peer_id,
            display_name,
            token,
            anilist_user_id,
            app_version,
        }) => (peer_id, display_name, token, anilist_user_id, app_version),
        Ok(_) => {
            reject(
                &connection,
                &mut sender,
                ErrorCode::Internal,
                "expected hello",
            )
            .await;
            return;
        }
        Err(_) => {
            reject(&connection, &mut sender, ErrorCode::Internal, "bad hello").await;
            return;
        }
    };
    let (peer_id, display_name, token, anilist_user_id, app_version) = hello;

    if token != inner.config.token {
        reject(&connection, &mut sender, ErrorCode::BadToken, "bad token").await;
        return;
    }

    // Mixed app versions break the room silently later; refuse them at the door.
    if app_version != env!("CARGO_PKG_VERSION") {
        let message = format!(
            "app version mismatch: host {}, peer {}",
            env!("CARGO_PKG_VERSION"),
            if app_version.is_empty() {
                "pre-versioning"
            } else {
                app_version.as_str()
            }
        );
        reject(&connection, &mut sender, ErrorCode::BadVersion, &message).await;
        return;
    }

    let room_full = {
        let peers = inner.peers.lock().expect("session peers poisoned");
        let active = peers.values().filter(|entry| !entry.left).count();
        active >= inner.config.max_peers && !peers.contains_key(&peer_id)
    };
    if room_full {
        reject(&connection, &mut sender, ErrorCode::RoomFull, "room full").await;
        return;
    }

    let (out_tx, mut out_rx) = mpsc::unbounded_channel::<ServerMessage>();
    let last_seen = Arc::new(AtomicU64::new(now_ms()));
    // The dialable endpoint is read from the QUIC handshake, never from a
    // peer-supplied field: the endpoint id is the peer's public key.
    let endpoint_id = connection.remote_id().to_string();
    // After a handover a reconnecting peer keeps its role and readiness.
    let prior = inner.carried_entry(&peer_id);
    {
        let mut peers = inner.peers.lock().expect("session peers poisoned");
        peers.insert(
            peer_id.clone(),
            PeerEntry {
                peer_id: peer_id.clone(),
                display_name: display_name.clone(),
                anilist_user_id,
                role: prior.as_ref().map_or(Role::Viewer, |peer| peer.role),
                ready: prior.as_ref().is_some_and(|peer| peer.ready),
                stale: false,
                left: false,
                endpoint_id,
                last_seen_ms: last_seen.clone(),
                outbound: out_tx,
            },
        );
    }
    let _ = inner.events.send(HostEvent::PeerJoined {
        peer_id: peer_id.clone(),
        display_name: display_name.clone(),
    });

    let welcome = ServerMessage::Welcome {
        protocol: PROTOCOL_VERSION,
        session_id: inner.config.session_id.clone(),
        host_id: inner.config.host_peer_id.clone(),
        your_peer_id: peer_id.clone(),
        roster: inner.roster(),
        media_plan: inner.plan(),
    };
    if sender.send(&welcome).await.is_err() {
        inner.remove_peer(&peer_id);
        return;
    }
    inner.broadcast_roster();

    // Send the room's current playback so a (re)joining peer lands on the
    // authoritative position/pause instead of waiting for the next publish.
    // This is what keeps a room paused across a crash promotion (lobby.md §14.7):
    // the successor seeds a paused snapshot and every returning guest gets it.
    if let Some(state) = inner
        .playback
        .lock()
        .expect("session playback poisoned")
        .clone()
    {
        inner.send_to(
            &peer_id,
            ServerMessage::PlaybackState {
                revision: state.revision,
                media_id: state.media_id,
                position: state.position,
                is_playing: state.is_playing,
                rate: state.rate,
                updated_at_mono: state.updated_at_mono,
            },
        );
    }

    if let Some(waiting) = inner.waiting_state() {
        inner.send_to(
            &peer_id,
            ServerMessage::WaitingFor {
                item_id: waiting.item_id,
                peer_ids: waiting.peer_ids,
            },
        );
    }

    let writer = tokio::spawn(async move {
        while let Some(message) = out_rx.recv().await {
            if sender.send(&message).await.is_err() {
                break;
            }
        }
        sender.finish();
    });

    while let Ok(frame) = reader.recv().await {
        last_seen.store(now_ms(), Ordering::Relaxed);
        let outgoing = match frame.client() {
            Ok(ClientMessage::TimePing { id, t1 }) => Some(ServerMessage::TimePong {
                id,
                t1,
                t2: now_ms() as f64,
            }),
            Ok(ClientMessage::Chat {
                id,
                text,
                reply_to,
                attachment,
            }) => {
                // Untrusted peer line: sanitize, bound, and anchor it before
                // it reaches the room; spammy peers are dropped silently.
                if inner.allow_chat(&peer_id, now_ms() as f64 / 1000.0) {
                    if let Some(text) = sanitize_chat_text(&text) {
                        let id = chat_id_or_generate(&id);
                        let reply_to =
                            reply_to.filter(|r| !r.is_empty() && r.len() <= CHAT_ID_MAX_CHARS);
                        // Viewers may talk but never attach: their upload is
                        // stripped while the text still goes through.
                        let upload = inner.accept_upload(&peer_id, attachment);
                        inner.add_chat(id, display_name.clone(), text, reply_to, upload);
                    }
                }
                None
            }
            Ok(ClientMessage::RequestControl { action }) => {
                inner.relay_control(action);
                None
            }
            Ok(ClientMessage::Typing { active }) => {
                // Relay the peer's typing state to the room (never back to
                // the sender) once it clears the throttle; stop frames are
                // unthrottled so indicators can always clear.
                if inner.allow_typing(&peer_id, active, now_ms() as f64 / 1000.0) {
                    inner.broadcast_except(
                        &peer_id,
                        ServerMessage::Typing {
                            peer_id: peer_id.clone(),
                            active,
                        },
                    );
                    let _ = inner.events.send(HostEvent::Typing {
                        peer_id: peer_id.clone(),
                        active,
                    });
                }
                None
            }
            Ok(ClientMessage::RequestStart { item_id }) => {
                if inner.can_start(&peer_id) {
                    let _ = inner.start_item(&item_id);
                }
                None
            }
            Ok(ClientMessage::HandoverReady { endpoint_id }) => {
                // Unmatched replies are ignored (the waiter names its peer).
                inner.resolve_handover(&peer_id, endpoint_id);
                None
            }
            Ok(ClientMessage::RequestTrackSync) => {
                inner.last_track().map(|track| ServerMessage::TrackSync {
                    media_id: track.media_id,
                    audio: track.audio,
                    sub: track.sub,
                    audio_delay: track.audio_delay,
                    sub_delay: track.sub_delay,
                })
            }
            Ok(ClientMessage::TrackPick {
                audio,
                sub,
                audio_delay,
                sub_delay,
            }) => {
                let media_id = inner
                    .playback
                    .lock()
                    .expect("session playback poisoned")
                    .as_ref()
                    .map_or_else(String::new, |state| state.media_id.clone());
                inner.set_track(TrackState {
                    media_id,
                    audio,
                    sub,
                    audio_delay,
                    sub_delay,
                });
                None
            }
            Ok(ClientMessage::StateReport { ready, items, .. }) => {
                inner.record_state_report(&peer_id, ready, items);
                None
            }
            Ok(ClientMessage::Bye) => break,
            Err(ProtocolError::FrameTooLarge) => Some(ServerMessage::Error {
                code: ErrorCode::RateLimited,
                message: "frame too large".to_string(),
            }),
            _ => None,
        };
        if let Some(message) = outgoing {
            inner.send_to(&peer_id, message);
        }
    }

    inner.remove_peer(&peer_id);
    connection.close(0u32.into(), b"bye");
    let _ = writer.await;
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn generated_config_is_well_formed() {
        let config = HostConfig::generate("Host".into());
        assert_eq!(config.session_id.len(), 16);
        assert_eq!(config.token.len(), 32);
        assert_eq!(config.host_peer_id.len(), 16);
        assert_eq!(config.max_peers, DEFAULT_MAX_PEERS);
        assert_ne!(config.token, HostConfig::generate("Host".into()).token);
    }

    #[tokio::test]
    async fn roster_starts_with_only_the_host() {
        let endpoint = transport::bind_offline_endpoint().await.expect("endpoint");
        let session = HostSession::bind(HostConfig::generate("Host".into()), endpoint);
        let roster = session.roster();
        assert_eq!(roster.len(), 1);
        assert_eq!(roster[0].role, Role::Host);
        assert_eq!(roster[0].peer_id, session.host_peer_id());
        assert_eq!(session.peer_count(), 0);
        session.stop().await;
    }

    #[tokio::test]
    async fn handover_rejects_self_and_unknown_peers() {
        let endpoint = transport::bind_offline_endpoint().await.expect("endpoint");
        let session = HostSession::bind(HostConfig::generate("Host".into()), endpoint);
        assert!(session.begin_handover(session.host_peer_id()).is_err());
        assert!(session.begin_handover("nobody").is_err());
        session.stop().await;
    }

    #[tokio::test]
    async fn peers_past_grace_are_marked_left_and_pause_the_room() {
        let endpoint = transport::bind_offline_endpoint().await.expect("endpoint");
        let session = HostSession::bind(HostConfig::generate("Host".into()), endpoint);
        let inner = session.inner.clone();
        inner.insert_test_peer("guest-1", Role::Viewer);
        session.publish_position("ep1".into(), 30.0, true, 1.0);

        // Fresh: alive, no left marker.
        let now = now_ms();
        assert!(inner.apply_liveness(now).is_empty());
        assert!(!session.roster().iter().any(|peer| peer.left));

        // Past the grace window the peer is marked left and the room pauses.
        let left = inner.apply_liveness(now + LIVENESS_GRACE_MS + 1);
        assert_eq!(left, vec!["guest-1".to_string()]);
        let peer = session
            .roster()
            .into_iter()
            .find(|peer| peer.peer_id == "guest-1")
            .expect("a left peer stays in the roster");
        assert!(peer.left);
        assert_eq!(peer.connection, ConnectionState::Disconnected);
        assert!(!session.last_playback().expect("snapshot").is_playing);
        // Re-marking does not re-trigger a left transition.
        assert!(inner.apply_liveness(now + LIVENESS_GRACE_MS + 2).is_empty());

        // A reconnect clears the marker.
        inner.insert_test_peer("guest-1", Role::Viewer);
        let peer = session
            .roster()
            .into_iter()
            .find(|peer| peer.peer_id == "guest-1")
            .expect("peer");
        assert!(!peer.left);

        session.stop().await;
    }

    #[tokio::test]
    async fn a_left_peer_clears_the_hold_without_starting() {
        let endpoint = transport::bind_offline_endpoint().await.expect("endpoint");
        let session = HostSession::bind(HostConfig::generate("Host".into()), endpoint);
        let inner = session.inner.clone();
        inner.insert_test_peer("guest-1", Role::Viewer);
        session.set_plan(vec![plan_item("a")], std::collections::HashMap::new());

        // guest-1 never reported item a: the start is held.
        assert!(matches!(
            session.start_item("a").expect("hold"),
            StartOutcome::Waiting { .. }
        ));
        assert!(session.waiting().is_some());

        inner.apply_liveness(now_ms() + LIVENESS_GRACE_MS + 1);
        // The hold is over once the left peer stops gating the room, but
        // nothing auto-starts: the last snapshot is the paused hold.
        assert!(session.waiting().is_none());
        let playback = session.last_playback().expect("paused hold snapshot");
        assert!(!playback.is_playing);

        session.stop().await;
    }

    fn plan_item(id: &str) -> MediaPlanItem {
        MediaPlanItem {
            item_id: id.into(),
            order: 0,
            title: id.into(),
            identity: crate::session::protocol::MediaIdentity {
                sha256: "0".repeat(64),
                size: 1,
                duration: 1.0,
                video: None,
            },
            sources: Vec::new(),
        }
    }

    #[tokio::test]
    async fn chat_rate_limit_opens_a_sliding_window_per_peer() {
        let endpoint = transport::bind_offline_endpoint().await.expect("endpoint");
        let session = HostSession::bind(HostConfig::generate("Host".into()), endpoint);
        let inner = session.inner.clone();

        let now = 1_000.0;
        for _ in 0..CHAT_RATE_MAX {
            assert!(inner.allow_chat("peer-a", now));
        }
        assert!(!inner.allow_chat("peer-a", now));
        // A different peer has its own window.
        assert!(inner.allow_chat("peer-b", now));
        // The window slides.
        assert!(inner.allow_chat("peer-a", now + CHAT_RATE_WINDOW_SEC + 1.0));
        session.stop().await;
    }

    #[tokio::test]
    async fn typing_frames_throttle_starts_but_never_stops() {
        let endpoint = transport::bind_offline_endpoint().await.expect("endpoint");
        let session = HostSession::bind(HostConfig::generate("Host".into()), endpoint);
        let inner = session.inner.clone();

        let now = 1_000.0;
        // The first start frame lands; a second inside the gap is dropped...
        assert!(inner.allow_typing("peer-a", true, now));
        assert!(!inner.allow_typing("peer-a", true, now + 0.1));
        // ...but a stop frame always passes so the indicator can clear...
        assert!(inner.allow_typing("peer-a", false, now + 0.1));
        // ...and the next start lands once the gap has elapsed.
        assert!(inner.allow_typing("peer-a", true, now + TYPING_MIN_INTERVAL_SEC + 0.1));
        // Another peer has its own throttle.
        assert!(inner.allow_typing("peer-b", true, now + 0.1));
        session.stop().await;
    }

    #[tokio::test]
    async fn plan_starts_empty_and_opens_the_solo_gate() {
        let endpoint = transport::bind_offline_endpoint().await.expect("endpoint");
        let session = HostSession::bind(HostConfig::generate("Host".into()), endpoint);
        assert!(session.plan().is_empty());
        // No plan: the gate stays closed even for a ready host.
        assert!(!session.ready_summary().all_ready);

        session.set_plan(
            vec![plan_item("a"), plan_item("b")],
            std::collections::HashMap::new(),
        );
        assert_eq!(session.plan().len(), 2);
        assert_eq!(session.plan()[0].item_id, "a");
        // A solo host with a plan opens the gate.
        let summary = session.ready_summary();
        assert!(summary.all_ready);
        assert_eq!(summary.peers.len(), 1);
        assert!(summary.peers[0].ready);
        session.stop().await;
    }

    #[tokio::test]
    async fn publish_position_stamps_revision_and_clock() {
        let endpoint = transport::bind_offline_endpoint().await.expect("endpoint");
        let session = HostSession::bind(HostConfig::generate("Host".into()), endpoint);
        let first = session.publish_position("ep1".into(), 12.0, true, 1.0);
        let second = session.publish_position("ep1".into(), 13.0, false, 1.5);
        assert!(second.revision > first.revision);
        assert!(first.updated_at_mono > 0.0);
        assert_eq!(
            session.last_playback().map(|state| state.position),
            Some(13.0)
        );
        session.stop().await;
    }

    #[test]
    fn liveness_boundaries_match_the_locked_windows() {
        let now = 1_000_000;
        assert_eq!(peer_liveness(now, now - 1_000, false), PeerLiveness::Alive);
        assert_eq!(
            peer_liveness(now, now - LIVENESS_TIMEOUT_MS, false),
            PeerLiveness::Alive
        );
        assert_eq!(
            peer_liveness(now, now - LIVENESS_TIMEOUT_MS - 1, false),
            PeerLiveness::Stale
        );
        // Already stale stays stale without re-triggering a change.
        assert_eq!(
            peer_liveness(now, now - LIVENESS_TIMEOUT_MS - 1, true),
            PeerLiveness::Alive
        );
        assert_eq!(
            peer_liveness(now, now - LIVENESS_GRACE_MS, true),
            PeerLiveness::Alive
        );
        assert_eq!(
            peer_liveness(now, now - LIVENESS_GRACE_MS - 1, true),
            PeerLiveness::Drop
        );
    }

    #[tokio::test]
    async fn control_relay_bumps_revision_and_emits_events() {
        let endpoint = transport::bind_offline_endpoint().await.expect("endpoint");
        let session = HostSession::bind(HostConfig::generate("Host".into()), endpoint);
        let mut events = session.subscribe();

        let first = session.relay_control(ControlAction::Pause);
        let second = session.relay_control(ControlAction::Play);
        assert!(second > first, "revision must advance across relays");
        assert!(matches!(
            events.recv().await.expect("control event"),
            HostEvent::Control {
                revision,
                action: ControlAction::Pause
            } if revision == first
        ));
        assert!(matches!(
            events.recv().await.expect("control event"),
            HostEvent::Control {
                revision,
                action: ControlAction::Play
            } if revision == second
        ));

        session.stop().await;
    }

    #[tokio::test]
    async fn publish_playback_stores_without_restamping_the_revision() {
        let endpoint = transport::bind_offline_endpoint().await.expect("endpoint");
        let session = HostSession::bind(HostConfig::generate("Host".into()), endpoint);

        session.publish_playback(PlaybackState {
            revision: 9,
            media_id: "ep1".into(),
            position: 5.0,
            is_playing: false,
            rate: 1.0,
            updated_at_mono: 42.0,
        });
        let stored = session.last_playback().expect("stored playback");
        assert_eq!(stored.revision, 9);
        assert_eq!(stored.position, 5.0);
        assert_eq!(stored.media_id, "ep1");

        session.stop().await;
    }

    #[tokio::test]
    async fn track_sync_stores_and_emits_the_selection() {
        let endpoint = transport::bind_offline_endpoint().await.expect("endpoint");
        let session = HostSession::bind(HostConfig::generate("Host".into()), endpoint);
        let mut events = session.subscribe();

        session.sync_tracks(TrackState {
            media_id: "ep1".into(),
            audio: Some("jpn".into()),
            sub: Some("eng".into()),
            audio_delay: 0.0,
            sub_delay: 2.0,
        });
        assert!(matches!(
            events.recv().await.expect("track event"),
            HostEvent::Track { track } if track.sub.as_deref() == Some("eng")
        ));
        assert_eq!(
            session.last_track().and_then(|track| track.audio),
            Some("jpn".into())
        );

        session.stop().await;
    }

    #[tokio::test]
    async fn roles_gate_start_and_paths_stay_host_local() {
        let endpoint = transport::bind_offline_endpoint().await.expect("endpoint");
        let session = HostSession::bind(HostConfig::generate("Host".into()), endpoint);

        let mut paths = HashMap::new();
        paths.insert("a".to_string(), "C:/a.mkv".to_string());
        paths.insert("stale".to_string(), "C:/stale.mkv".to_string());
        session.set_plan(vec![plan_item("a")], paths);
        // Paths are pruned to the plan ids and kept on the host only.
        assert_eq!(session.inner.item_path("a").as_deref(), Some("C:/a.mkv"));
        assert_eq!(session.inner.item_path("stale"), None);

        session.inner.insert_test_peer("guest-1", Role::Viewer);
        assert!(!session.inner.can_start("guest-1"));
        // Promotion opens start rights for the moderator.
        session
            .set_role("guest-1", Role::Moderator)
            .expect("promote");
        assert!(session.inner.can_start("guest-1"));
        // The host role is immutable and no guest can become host.
        let host_id = session.host_peer_id().to_string();
        assert!(session.set_role(&host_id, Role::Viewer).is_err());
        assert!(session.set_role("guest-1", Role::Host).is_err());
        // Demotion closes them again.
        session.set_role("guest-1", Role::Viewer).expect("demote");
        assert!(!session.inner.can_start("guest-1"));
        assert!(session.set_role("missing", Role::Moderator).is_err());

        session.stop().await;
    }

    #[tokio::test]
    async fn chat_uploads_need_host_or_moderator_rights() {
        let endpoint = transport::bind_offline_endpoint().await.expect("endpoint");
        let session = HostSession::bind(HostConfig::generate("Host".into()), endpoint);
        session.inner.insert_test_peer("guest-1", Role::Viewer);

        let upload = || {
            Some(ChatUpload {
                name: "show.torrent".into(),
                data: STANDARD.encode(b"d8:announce4:test e"),
            })
        };
        // Viewers may talk but never attach.
        assert!(!session.inner.can_attach("guest-1"));
        assert_eq!(session.inner.accept_upload("guest-1", upload()), None);
        // Promotion opens attach rights for the moderator.
        session
            .set_role("guest-1", Role::Moderator)
            .expect("promote");
        assert!(session.inner.can_attach("guest-1"));
        let (name, bytes) = session
            .inner
            .accept_upload("guest-1", upload())
            .expect("moderator upload accepted");
        assert_eq!(name, "show.torrent");
        assert_eq!(bytes, b"d8:announce4:test e");
        // Corrupt payloads and wrong names never pass, whatever the role.
        assert_eq!(
            session.inner.accept_upload(
                "guest-1",
                Some(ChatUpload {
                    name: "show.torrent".into(),
                    data: "!!!".into(),
                })
            ),
            None
        );
        assert_eq!(
            session.inner.accept_upload(
                "guest-1",
                Some(ChatUpload {
                    name: "clip.mkv".into(),
                    data: STANDARD.encode(b"x"),
                })
            ),
            None
        );
        assert_eq!(session.inner.accept_upload("missing", upload()), None);

        // The stored message carries metadata only; bytes ride the wire form.
        let message = session.inner.add_chat(
            "m1".into(),
            "Host".into(),
            String::new(),
            None,
            Some(("show.torrent".into(), b"bytes".to_vec())),
        );
        assert_eq!(
            message.attachment,
            Some(ChatAttachment {
                name: "show.torrent".into(),
                size: 5,
            })
        );

        session.stop().await;
    }

    #[tokio::test]
    async fn start_item_holds_until_missing_peers_report_then_never_auto_starts() {
        let endpoint = transport::bind_offline_endpoint().await.expect("endpoint");
        let session = HostSession::bind(HostConfig::generate("Host".into()), endpoint);
        let mut events = session.subscribe();
        session.set_plan(vec![plan_item("a")], HashMap::new());
        session.inner.insert_test_peer("guest-1", Role::Viewer);

        // A peer without the file holds the start instead of beginning playback.
        let outcome = session.start_item("a").expect("start");
        assert!(matches!(
            outcome,
            StartOutcome::Waiting { item_id, ref peer_ids }
                if item_id == "a" && peer_ids == &vec!["guest-1".to_string()]
        ));
        assert_eq!(
            session.waiting().map(|waiting| waiting.peer_ids),
            Some(vec!["guest-1".to_string()])
        );
        assert!(matches!(
            events.recv().await.expect("waiting event"),
            HostEvent::Waiting { ref peer_ids, .. } if peer_ids == &vec!["guest-1".to_string()]
        ));

        // The guest reports the file; the wait clears but playback does not start.
        session.inner.record_state_report(
            "guest-1",
            true,
            vec![ItemReport {
                item_id: "a".into(),
                present: true,
                verified: true,
            }],
        );
        assert!(session.waiting().is_none());
        assert!(matches!(
            events.recv().await.expect("clear event"),
            HostEvent::Waiting { ref peer_ids, .. } if peer_ids.is_empty()
        ));

        // A fresh start now begins playback and reports the host-local path.
        let mut paths = HashMap::new();
        paths.insert("a".to_string(), "C:/a.mkv".to_string());
        session.set_plan(vec![plan_item("a")], paths);
        let outcome = session.start_item("a").expect("start");
        assert!(matches!(
            outcome,
            StartOutcome::Started { ref item_id, ref path }
                if item_id == "a" && path.as_deref() == Some("C:/a.mkv")
        ));
        // A successful start first clears the banner, then starts the item.
        assert!(matches!(
            events.recv().await.expect("clear event"),
            HostEvent::Waiting { ref peer_ids, .. } if peer_ids.is_empty()
        ));
        assert!(matches!(
            events.recv().await.expect("start event"),
            HostEvent::StartItem { ref item_id, ref path }
                if item_id == "a" && path.as_deref() == Some("C:/a.mkv")
        ));
        assert!(session.start_item("missing").is_err());

        session.stop().await;
    }

    #[tokio::test]
    async fn stop_is_idempotent_and_keeps_the_solo_roster() {
        let endpoint = transport::bind_offline_endpoint().await.expect("endpoint");
        let session = HostSession::bind(HostConfig::generate("Host".into()), endpoint);
        assert_eq!(session.peer_count(), 0);

        session.stop().await;
        session.stop().await;

        let roster = session.roster();
        assert_eq!(roster.len(), 1);
        assert_eq!(roster[0].peer_id, session.host_peer_id());
    }
}
