// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
  getBackendCapabilities: () =>
    __TAURI_INVOKE<BackendCapabilities>("get_backend_capabilities"),
};

/* Types */
export interface BackendCapabilities {
  apiVersion: string;
  typedIpc: boolean;
}
